/*
 * Licensed Materials - Property of IBM
 *
 * 5724-U18
 *
 * (C) Copyright IBM Corp. 2017 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with
 * IBM Corp.
 */

var resultRecord = [{
  'status_description': 'In Progress',
  'createdate': '2017-03-23T14:35:39-04:00',
  'resultnum': '1171',
  '$alias_this_attr$asset': '11200',
  'revision': 1,
  '_rowstamp': '[0 0 0 0 0 27 127 -49]',
  'orgid': 'EAGLENA',
  '_id': 'EAGLENA-1171-BEDFORD',
  'locations': {},
  'inspectionform': [
    {
      'changedate': '2017-03-23T14:35:14-04:00',
      'hasld_localized': 'Y',
      'inspectionformid': 911,
      'description_longdescription': '<p>Test Instructions for --Test Inspection Form--</p>',
      'status_description': 'Active',
      'createdate': '2017-03-23T14:30:09-04:00',
      'hasrevision': false,
      'langcode': 'EN',
      'hasrevision_localized': 'N',
      'revision': 1,
      '_rowstamp': '[0 0 0 0 0 27 127 -72]',
      '_id': '1122-EAGLENA-1',
      'name': 'Test Inspection Form',
      'revision_localized': '1',
      'inspformnum': '1122',
      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS8xMTIyL0VBR0xFTkEvMQ--',
      'status_maxvalue': 'ACTIVE',
      'inspquestion_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion',
      'changedate_localized': '3/23/17 2:35 PM',
      'status': 'ACTIVE',
      'changeby': 'THEO',
      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911',
      'createdby': 'THEO',
      'inspectionformid_localized': '911',
      'inspquestion': [
        {
          'groupseq_localized': '1.00',
          'groupseq': 1,
          'hasld_localized': 'N',
          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907',
          'langcode': 'EN',
          'inspquestionnum': '1256',
          'inspfield': [
            {
              'hasld_localized': 'N',
              'showdate_localized': 'N',
              'langcode': 'EN',
              'revision': 1,
              '_rowstamp': '[0 0 0 0 0 27 127 2]',
              '_id': '1137-1122-1256-EAGLENA-1',
              'orgid': 'EAGLENA',
              'showdate': false,
              'description': 'Text Response 1 for Question A (Not Required):',
              'revision_localized': '1',
              'inspformnum': '1122',
              'showtime': false,
              'required': false,
              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExMzcvMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
              'required_localized': 'N',
              'inspfieldid_localized': '811',
              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldoption',
              'fieldtype': 'TR',
              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811',
              'showtime_localized': 'N',
              'inspfieldnum': '1137',
              'inspquestionnum': '1256',
              'sequence': 1,
              'sequence_localized': '1',
              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldresult',
              'inspfieldid': 811,
              'hasld': false
            },
            {
              'hasld_localized': 'N',
              'showdate_localized': 'N',
              'langcode': 'EN',
              'revision': 1,
              '_rowstamp': '[0 0 0 0 0 27 127 1]',
              '_id': '1138-1122-1256-EAGLENA-1',
              'orgid': 'EAGLENA',
              'showdate': false,
              'description': 'Text Response 2 for Quesion A (Required)',
              'revision_localized': '1',
              'inspformnum': '1122',
              'showtime': false,
              'required': true,
              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExMzgvMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
              'required_localized': 'Y',
              'inspfieldid_localized': '812',
              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/1-812/inspfieldoption',
              'fieldtype': 'TR',
              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/1-812',
              'showtime_localized': 'N',
              'inspfieldnum': '1138',
              'inspquestionnum': '1256',
              'sequence': 2,
              'sequence_localized': '2',
              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/1-812/inspfieldresult',
              'inspfieldid': 812,
              'hasld': false
            },
            {
              'hasld_localized': 'N',
              'showdate_localized': 'N',
              'langcode': 'EN',
              'revision': 1,
              '_rowstamp': '[0 0 0 0 0 27 126 -1]',
              '_id': '1139-1122-1256-EAGLENA-1',
              'orgid': 'EAGLENA',
              'showdate': false,
              'description': 'Test Numeric Response 1 for Question A (Required)',
              'revision_localized': '1',
              'inspformnum': '1122',
              'showtime': false,
              'required': true,
              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExMzkvMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
              'required_localized': 'Y',
              'inspfieldid_localized': '813',
              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/2-813/inspfieldoption',
              'fieldtype': 'SE',
              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/2-813',
              'showtime_localized': 'N',
              'inspfieldnum': '1139',
              'inspquestionnum': '1256',
              'sequence': 3,
              'sequence_localized': '3',
              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/2-813/inspfieldresult',
              'inspfieldid': 813,
              'hasld': false
            },
            {
              'hasld_localized': 'N',
              'showdate_localized': 'N',
              'langcode': 'EN',
              'revision': 1,
              '_rowstamp': '[0 0 0 0 0 27 126 -2]',
              '_id': '1140-1122-1256-EAGLENA-1',
              'orgid': 'EAGLENA',
              'showdate': false,
              'description': 'Test Numeric Response 2 for  Question A (Not Required)',
              'revision_localized': '1',
              'inspformnum': '1122',
              'showtime': false,
              'required': false,
              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDAvMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
              'required_localized': 'N',
              'inspfieldid_localized': '814',
              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/3-814/inspfieldoption',
              'fieldtype': 'SE',
              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/3-814',
              'showtime_localized': 'N',
              'inspfieldnum': '1140',
              'inspquestionnum': '1256',
              'sequence': 4,
              'sequence_localized': '4',
              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/3-814/inspfieldresult',
              'inspfieldid': 814,
              'hasld': false
            }
          ],
          '_rowstamp': '[0 0 0 0 0 27 126 -3]',
          'inspquestionid_localized': '907',
          '_id': '1122-1256-EAGLENA-1',
          'sequence': 1,
          'description': 'What is in Question A?',
          'sequence_localized': '1',
          'inspquestionid': 907,
          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield',
          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
          'hasld': false,
          'required': true,
          '_done': false,
          'listdesc': '1. What is in Question A?'
        },
        {
          'groupseq_localized': '2.00',
          'groupseq': 2,
          'hasld_localized': 'N',
          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908',
          'langcode': 'EN',
          'inspquestionnum': '1257',
          'inspfield': [
            {
              'hasld_localized': 'N',
              'showdate_localized': 'N',
              'langcode': 'EN',
              'revision': 1,
              '_rowstamp': '[0 0 0 0 0 27 127 33]',
              '_id': '1141-1122-1257-EAGLENA-1',
              'orgid': 'EAGLENA',
              'showdate': false,
              'revision_localized': '1',
              'inspformnum': '1122',
              'showtime': false,
              'required': false,
              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDEvMTEyMi8xMjU3L0VBR0xFTkEvMQ--',
              'required_localized': 'N',
              'inspfieldid_localized': '815',
              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908/inspfield/0-815/inspfieldoption',
              'fieldtype': 'TR',
              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908/inspfield/0-815',
              'inspfieldnum': '1141',
              'showtime_localized': 'N',
              'inspquestionnum': '1257',
              'sequence': 1,
              'sequence_localized': '1',
              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908/inspfield/0-815/inspfieldresult',
              'inspfieldid': 815,
              'hasld': false
            }
          ],
          '_rowstamp': '[0 0 0 0 0 27 127 93]',
          'inspquestionid_localized': '908',
          '_id': '1122-1257-EAGLENA-1',
          'sequence': 2,
          'description': 'Question B - Contains labelless response',
          'sequence_localized': '2',
          'inspquestionid': 908,
          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908/inspfield',
          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyMi8xMjU3L0VBR0xFTkEvMQ--',
          'hasld': false,
          '_done': false,
          'listdesc': '2. Question B - Contains labelless response'
        },
        {
          'groupseq_localized': '3.00',
          'groupseq': 3,
          'hasld_localized': 'N',
          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/3-910',
          'langcode': 'EN',
          'inspquestionnum': '1259',
          'inspquestionid_localized': '910',
          '_rowstamp': '[0 0 0 0 0 27 127 -73]',
          '_id': '1122-1259-EAGLENA-1',
          'sequence': 0,
          'description': 'Group Containing - Question C',
          'groupid_localized': '3',
          'sequence_localized': '0',
          'inspquestionid': 910,
          'groupid': 3,
          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/3-910/inspfield',
          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyMi8xMjU5L0VBR0xFTkEvMQ--',
          'hasld': false,
          '_done': false,
          'listdesc': '3. Group Containing - Question C',
          'children': [
            {
              'groupseq_localized': '3.10',
              'groupseq': 3.1,
              'hasld_localized': 'N',
              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909',
              'langcode': 'EN',
              'inspquestionnum': '1258',
              'inspfield': [
                {
                  'hasld_localized': 'N',
                  'showdate_localized': 'N',
                  'langcode': 'EN',
                  'revision': 1,
                  '_rowstamp': '[0 0 0 0 0 27 127 -114]',
                  '_id': '1142-1122-1258-EAGLENA-1',
                  'orgid': 'EAGLENA',
                  'showdate': false,
                  'description': 'Required Response',
                  'revision_localized': '1',
                  'inspformnum': '1122',
                  'showtime': false,
                  'required': true,
                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDIvMTEyMi8xMjU4L0VBR0xFTkEvMQ--',
                  'required_localized': 'Y',
                  'inspfieldid_localized': '816',
                  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909/inspfield/0-816/inspfieldoption',
                  'fieldtype': 'TR',
                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909/inspfield/0-816',
                  'showtime_localized': 'N',
                  'inspfieldnum': '1142',
                  'inspquestionnum': '1258',
                  'sequence': 1,
                  'sequence_localized': '1',
                  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909/inspfield/0-816/inspfieldresult',
                  'inspfieldid': 816,
                  'hasld': false
                }
              ],
              'inspquestionid_localized': '909',
              '_rowstamp': '[0 0 0 0 0 27 127 -86]',
              '_id': '1122-1258-EAGLENA-1',
              'sequence': 1,
              'description': 'Question C',
              'groupid_localized': '3',
              'sequence_localized': '1',
              'inspquestionid': 909,
              'groupid': 3,
              'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909/inspfield',
              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyMi8xMjU4L0VBR0xFTkEvMQ--',
              'hasld': false,
              'required': true,
              '_done': false,
              'listdesc': '3.1. Question C'
            }
          ]
        },
        {
          'groupseq_localized': '3.10',
          'groupseq': 3.1,
          'hasld_localized': 'N',
          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909',
          'langcode': 'EN',
          'inspquestionnum': '1258',
          'inspfield': [
            {
              'hasld_localized': 'N',
              'showdate_localized': 'N',
              'langcode': 'EN',
              'revision': 1,
              '_rowstamp': '[0 0 0 0 0 27 127 -114]',
              '_id': '1142-1122-1258-EAGLENA-1',
              'orgid': 'EAGLENA',
              'showdate': false,
              'description': 'Required Response',
              'revision_localized': '1',
              'inspformnum': '1122',
              'showtime': false,
              'required': true,
              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDIvMTEyMi8xMjU4L0VBR0xFTkEvMQ--',
              'required_localized': 'Y',
              'inspfieldid_localized': '816',
              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909/inspfield/0-816/inspfieldoption',
              'fieldtype': 'TR',
              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909/inspfield/0-816',
              'showtime_localized': 'N',
              'inspfieldnum': '1142',
              'inspquestionnum': '1258',
              'sequence': 1,
              'sequence_localized': '1',
              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909/inspfield/0-816/inspfieldresult',
              'inspfieldid': 816,
              'hasld': false
            }
          ],
          'inspquestionid_localized': '909',
          '_rowstamp': '[0 0 0 0 0 27 127 -86]',
          '_id': '1122-1258-EAGLENA-1',
          'sequence': 1,
          'description': 'Question C',
          'groupid_localized': '3',
          'sequence_localized': '1',
          'inspquestionid': 909,
          'groupid': 3,
          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/2-909/inspfield',
          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyMi8xMjU4L0VBR0xFTkEvMQ--',
          'hasld': false,
          'required': true,
          '_done': false,
          'listdesc': '3.1. Question C'
        }
      ],
      'createdate_localized': '3/23/17 2:30 PM',
      'hasld': true
    }
  ],
  'revision_localized': '1',
  'inspformnum': '1122',
  'siteid': 'BEDFORD',
  'href': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-',
  'status_maxvalue': 'INPROG',
  'inspresultstatus_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspresultstatus',
  'asset': {
    'description': 'HVAC System- 50 Ton Cool Cap/ 450000 Btu Heat Cap'
  },
  'status': 'INPROG',
  'inspectionresultid': 433,
  'inspresultstatus': [
    {
      'changedate': '2017-03-23T14:35:39-04:00',
      'changedate_localized': '3/23/17 2:35 PM',
      'status_description': 'In Progress',
      'status': 'INPROG',
      'changeby': 'ALVIN',
      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspresultstatus/0-416',
      '_rowstamp': '[0 0 0 0 0 27 127 -48]',
      'inspresultstatusnum': '1058',
      '_id': '1058-EAGLENA-BEDFORD',
      'inspresultstatusid': 416,
      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQUkVTVUxUU1RBVFVTLzEwNTgvRUFHTEVOQS9CRURGT1JE',
      'inspresultstatusid_localized': '416',
      'status_maxvalue': 'INPROG'
    }
  ],
  'createdby': 'ALVIN',
  'inspectionresultid_localized': '433',
  'referenceobject': 'ASSET',
  'createdate_localized': '3/23/17 2:35 PM',
  'inspectionform_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform',
  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspfieldresult'
}];


var field = [{
  'hasld_localized': 'N',
  'showdate_localized': 'N',
  'langcode': 'EN',
  'revision': 1,
  '_rowstamp': '[0 0 0 0 0 27 127 2]',
  '_id': '1137-1122-1256-EAGLENA-1',
  'orgid': 'EAGLENA',
  'showdate': false,
  'description': 'Text Response 1 for Question A (Not Required):',
  'revision_localized': '1',
  'inspformnum': '1122',
  'showtime': false,
  'required': false,
  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExMzcvMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
  'required_localized': 'N',
  'inspfieldid_localized': '811',
  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldoption',
  'fieldtype': 'TR',
  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811',
  'showtime_localized': 'N',
  'inspfieldnum': '1137',
  'inspquestionnum': '1256',
  'sequence': 1,
  'sequence_localized': '1',
  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldresult',
  'inspfieldid': 811,
  'hasld': false
}];

var requiredfield = [{
	  'hasld_localized': 'N',
	  'showdate_localized': 'N',
	  'langcode': 'EN',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 27 127 2]',
	  '_id': '1137-1122-1256-EAGLENA-1',
	  'orgid': 'EAGLENA',
	  'showdate': false,
	  'description': 'Text Response 1 for Question A (Not Required):',
	  'revision_localized': '1',
	  'inspformnum': '1122',
	  'showtime': false,
	  'required': true,
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExMzcvMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
	  'required_localized': 'N',
	  'inspfieldid_localized': '811',
	  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldoption',
	  'fieldtype': 'TR',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811',
	  'showtime_localized': 'N',
	  'inspfieldnum': '1137',
	  'inspquestionnum': '1256',
	  'sequence': 1,
	  'sequence_localized': '1',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldresult',
	  'inspfieldid': 811,
	  'hasld': false
	}];

var numericfield = [{
	  'hasld_localized': 'N',
	  'showdate_localized': 'N',
	  'langcode': 'EN',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 27 127 2]',
	  '_id': '1137-1122-1256-EAGLENA-1',
	  'orgid': 'EAGLENA',
	  'showdate': false,
	  'description': 'Numeric Response 1 for Question A (Not Required):',
	  'revision_localized': '1',
	  'inspformnum': '1122',
	  'showtime': false,
	  'required': false,
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExMzcvMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
	  'required_localized': 'N',
	  'inspfieldid_localized': '811',
	  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldoption',
	  'fieldtype': 'SE',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811',
	  'showtime_localized': 'N',
	  'inspfieldnum': '1137',
	  'inspquestionnum': '1256',
	  'sequence': 1,
	  'sequence_localized': '1',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldresult',
	  'inspfieldid': 811,
	  'hasld': false
	}];

var requirednumericfield = [{
	  'hasld_localized': 'N',
	  'showdate_localized': 'N',
	  'langcode': 'EN',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 27 127 2]',
	  '_id': '1137-1122-1256-EAGLENA-1',
	  'orgid': 'EAGLENA',
	  'showdate': false,
	  'description': 'Numeric Response 1 for Question A (Required):',
	  'revision_localized': '1',
	  'inspformnum': '1122',
	  'showtime': false,
	  'required': true,
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExMzcvMTEyMi8xMjU2L0VBR0xFTkEvMQ--',
	  'required_localized': 'N',
	  'inspfieldid_localized': '811',
	  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldoption',
	  'fieldtype': 'SE',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811',
	  'showtime_localized': 'N',
	  'inspfieldnum': '1137',
	  'inspquestionnum': '1256',
	  'sequence': 1,
	  'sequence_localized': '1',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/0-907/inspfield/0-811/inspfieldresult',
	  'inspfieldid': 811,
	  'hasld': false
	}];

var question = [{
	  'groupseq_localized': '2.00',
	  'groupseq': 2,
	  'hasld_localized': 'N',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908',
	  'langcode': 'EN',
	  'inspquestionnum': '1257',
	  'inspfield': [
	    {
	      'hasld_localized': 'N',
	      'showdate_localized': 'N',
	      'langcode': 'EN',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 27 127 33]',
	      '_id': '1141-1122-1257-EAGLENA-1',
	      'orgid': 'EAGLENA',
	      'showdate': false,
	      'revision_localized': '1',
	      'inspformnum': '1122',
	      'showtime': false,
	      'required': false,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDEvMTEyMi8xMjU3L0VBR0xFTkEvMQ--',
	      'required_localized': 'N',
	      'inspfieldid_localized': '815',
	      'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908/inspfield/0-815/inspfieldoption',
	      'fieldtype': 'TR',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908/inspfield/0-815',
	      'inspfieldnum': '1141',
	      'showtime_localized': 'N',
	      'inspquestionnum': '1257',
	      'sequence': 1,
	      'sequence_localized': '1',
	      'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908/inspfield/0-815/inspfieldresult',
	      'inspfieldid': 815,
	      'hasld': false
	    }
	  ],
	  '_rowstamp': '[0 0 0 0 0 27 127 93]',
	  'inspquestionid_localized': '908',
	  '_id': '1122-1257-EAGLENA-1',
	  'sequence': 2,
	  'description': 'Question B - Contains labelless response',
	  'sequence_localized': '2',
	  'inspquestionid': 908,
	  'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTcxL0JFREZPUkQ-/inspectionform/0-911/inspquestion/1-908/inspfield',
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyMi8xMjU3L0VBR0xFTkEvMQ--',
	  'hasld': false,
	  '_done': false,
	  'listdesc': '2. Question B - Contains labelless response'
	}];


var resultRecordWithResponse = [{
	  'status_description': 'In Progress',
	  'createdate': '2017-03-23T20:32:56-04:00',
	  'resultnum': '1176',
	  '$alias_this_attr$asset': '11200',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 27 -27 -103]',
	  'orgid': 'EAGLENA',
	  '_id': 'EAGLENA-1176-BEDFORD',
	  'locations': {},
	  'inspectionform': [
	    {
	      'changedate': '2017-03-23T20:32:30-04:00',
	      'hasld_localized': 'N',
	      'inspectionformid': 913,
	      'status_description': 'Active',
	      'createdate': '2017-03-23T20:30:35-04:00',
	      'hasrevision': false,
	      'langcode': 'EN',
	      'hasrevision_localized': 'N',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 27 -27 97]',
	      '_id': '1123-EAGLENA-1',
	      'name': 'School Test Inspection',
	      'revision_localized': '1',
	      'inspformnum': '1123',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS8xMTIzL0VBR0xFTkEvMQ--',
	      'status_maxvalue': 'ACTIVE',
	      'inspquestion_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion',
	      'changedate_localized': '3/23/17 8:32 PM',
	      'changeby': 'THEO',
	      'status': 'ACTIVE',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913',
	      'createdby': 'THEO',
	      'inspectionformid_localized': '913',
	      'inspquestion': [
	        {
	          'groupseq_localized': '1.00',
	          'groupseq': 1,
	          'hasld_localized': 'N',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911',
	          'langcode': 'EN',
	          'inspquestionnum': '1260',
	          'inspfield': [
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  '_rowstamp': '[0 0 0 0 0 27 -27 7]',
	                  '_id': '36',
	                  'sequence': 2,
	                  'description': 'example 2',
	                  'inspfieldoptionid_localized': '36',
	                  'sequence_localized': '2',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817/inspfieldoption/0-36',
	                  'inspfieldoptionid': 36,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi8zNg--'
	                },
	                {
	                  '_rowstamp': '[0 0 0 0 0 27 -27 8]',
	                  '_id': '35',
	                  'sequence': 1,
	                  'description': 'example 1',
	                  'inspfieldoptionid_localized': '35',
	                  'sequence_localized': '1',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817/inspfieldoption/1-35',
	                  'inspfieldoptionid': 35,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi8zNQ--'
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 27 -27 6]',
	              '_id': '1143-1123-1260-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Text Response #1 Desc:',
	              'inspfieldresult': [
	                {
	                  'txtresponse': 'Answer to Question1 Response',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817/inspfieldresult/0-405',
	                  'inspfieldresultid': 405,
	                  'entereddate_localized': '3/23/17 8:33 PM',
	                  'resultnum': '1176',
	                  'inspfieldnum': '1143',
	                  'enteredby': 'ALVIN',
	                  'entereddate': '2017-03-23T20:33:20-04:00',
	                  'revision': 1,
	                  'inspquestionnum': '1260',
	                  '_rowstamp': '[0 0 0 0 0 27 -27 -85]',
	                  'orgid': 'EAGLENA',
	                  '_id': '1143-1123-1260-EAGLENA-1176-1-BEDFORD',
	                  'revision_localized': '1',
	                  'inspfieldresultnum': '1146',
	                  'siteid': 'BEDFORD',
	                  'inspformnum': '1123',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTQzLzExMjMvMTI2MC9FQUdMRU5BLzExNzYvMS9CRURGT1JE',
	                  'inspfieldresultid_localized': '405'
	                }
	              ],
	              'revision_localized': '1',
	              'inspformnum': '1123',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDMvMTEyMy8xMjYwL0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '817',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817/inspfieldoption',
	              'fieldtype': 'TR',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817',
	              'showtime_localized': 'N',
	              'inspfieldnum': '1143',
	              'inspquestionnum': '1260',
	              'sequence': 1,
	              'sequence_localized': '1',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817/inspfieldresult',
	              'inspfieldid': 817,
	              'hasld': false
	            }
	          ],
	          '_rowstamp': '[0 0 0 0 0 27 -27 5]',
	          'inspquestionid_localized': '911',
	          '_id': '1123-1260-EAGLENA-1',
	          'sequence': 1,
	          'description': 'What is your Question #1?',
	          'sequence_localized': '1',
	          'inspquestionid': 911,
	          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyMy8xMjYwL0VBR0xFTkEvMQ--',
	          'hasld': false,
	          '_done': true,
	          'listdesc': '1. What is your Question #1?'
	        },
	        {
	          'groupseq_localized': '2.00',
	          'groupseq': 2,
	          'hasld_localized': 'N',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912',
	          'langcode': 'EN',
	          'inspquestionnum': '1261',
	          'inspfield': [
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  '_rowstamp': '[0 0 0 0 0 27 -27 86]',
	                  '_id': '38',
	                  'sequence': 2,
	                  'description': 'example 2',
	                  'inspfieldoptionid_localized': '38',
	                  'sequence_localized': '2',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/0-818/inspfieldoption/0-38',
	                  'inspfieldoptionid': 38,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi8zOA--'
	                },
	                {
	                  '_rowstamp': '[0 0 0 0 0 27 -27 87]',
	                  '_id': '37',
	                  'sequence': 1,
	                  'description': 'example 1',
	                  'inspfieldoptionid_localized': '37',
	                  'sequence_localized': '1',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/0-818/inspfieldoption/1-37',
	                  'inspfieldoptionid': 37,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi8zNw--'
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 27 -27 85]',
	              '_id': '1144-1123-1261-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Text Response - Question 2:',
	              'inspfieldresult': [
	                {
	                  'txtresponse': 'Question 2 Response 1',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/0-818/inspfieldresult/0-406',
	                  'inspfieldresultid': 406,
	                  'entereddate_localized': '3/23/17 8:33 PM',
	                  'resultnum': '1176',
	                  'inspfieldnum': '1144',
	                  'enteredby': 'ALVIN',
	                  'entereddate': '2017-03-23T20:33:38-04:00',
	                  'revision': 1,
	                  'inspquestionnum': '1261',
	                  '_rowstamp': '[0 0 0 0 0 27 -27 -72]',
	                  'orgid': 'EAGLENA',
	                  '_id': '1144-1123-1261-EAGLENA-1176-1-BEDFORD',
	                  'revision_localized': '1',
	                  'inspfieldresultnum': '1147',
	                  'siteid': 'BEDFORD',
	                  'inspformnum': '1123',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTQ0LzExMjMvMTI2MS9FQUdMRU5BLzExNzYvMS9CRURGT1JE',
	                  'inspfieldresultid_localized': '406'
	                }
	              ],
	              'revision_localized': '1',
	              'inspformnum': '1123',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDQvMTEyMy8xMjYxL0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '818',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/0-818/inspfieldoption',
	              'fieldtype': 'TR',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/0-818',
	              'showtime_localized': 'N',
	              'inspfieldnum': '1144',
	              'inspquestionnum': '1261',
	              'sequence': 1,
	              'sequence_localized': '1',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/0-818/inspfieldresult',
	              'inspfieldid': 818,
	              'hasld': false
	            },
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  '_rowstamp': '[0 0 0 0 0 27 -27 88]',
	                  '_id': '40',
	                  'sequence': 2,
	                  'description': 'example 2',
	                  'inspfieldoptionid_localized': '40',
	                  'sequence_localized': '2',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819/inspfieldoption/0-40',
	                  'inspfieldoptionid': 40,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi80MA--'
	                },
	                {
	                  '_rowstamp': '[0 0 0 0 0 27 -27 89]',
	                  '_id': '39',
	                  'sequence': 1,
	                  'description': 'example 1',
	                  'inspfieldoptionid_localized': '39',
	                  'sequence_localized': '1',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819/inspfieldoption/1-39',
	                  'inspfieldoptionid': 39,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi8zOQ--'
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 27 -27 84]',
	              '_id': '1145-1123-1261-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Numeric Response - Question 2',
	              'inspfieldresult': [
	                {
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819/inspfieldresult/0-407',
	                  'inspfieldresultid': 407,
	                  'entereddate_localized': '3/23/17 8:33 PM',
	                  'resultnum': '1176',
	                  'inspfieldnum': '1145',
	                  'enteredby': 'ALVIN',
	                  'entereddate': '2017-03-23T20:33:50-04:00',
	                  'revision': 1,
	                  'inspquestionnum': '1261',
	                  '_rowstamp': '[0 0 0 0 0 27 -27 -27]',
	                  'orgid': 'EAGLENA',
	                  '_id': '1145-1123-1261-EAGLENA-1176-1-BEDFORD',
	                  'revision_localized': '1',
	                  'inspfieldresultnum': '1148',
	                  'siteid': 'BEDFORD',
	                  'inspformnum': '1123',
	                  'numresponse': '100.50',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTQ1LzExMjMvMTI2MS9FQUdMRU5BLzExNzYvMS9CRURGT1JE',
	                  'inspfieldresultid_localized': '407'
	                }
	              ],
	              'revision_localized': '1',
	              'inspformnum': '1123',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDUvMTEyMy8xMjYxL0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '819',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819/inspfieldoption',
	              'fieldtype': 'SE',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819',
	              'showtime_localized': 'N',
	              'inspfieldnum': '1145',
	              'inspquestionnum': '1261',
	              'sequence': 2,
	              'sequence_localized': '2',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819/inspfieldresult',
	              'inspfieldid': 819,
	              'hasld': false
	            }
	          ],
	          '_rowstamp': '[0 0 0 0 0 27 -27 83]',
	          'inspquestionid_localized': '912',
	          '_id': '1123-1261-EAGLENA-1',
	          'sequence': 2,
	          'description': 'Question 2?',
	          'sequence_localized': '2',
	          'inspquestionid': 912,
	          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyMy8xMjYxL0VBR0xFTkEvMQ--',
	          'hasld': false,
	          '_done': true,
	          'listdesc': '2. Question 2?'
	        }
	      ],
	      'createdate_localized': '3/23/17 8:30 PM',
	      'hasld': false
	    }
	  ],
	  'inspfieldresult': [
	    {
	      'txtresponse': 'Answer to Question1 Response',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspfieldresult/0-405',
	      'inspfieldresultid': 405,
	      'entereddate_localized': '3/23/17 8:33 PM',
	      'resultnum': '1176',
	      'inspfieldnum': '1143',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-03-23T20:33:20-04:00',
	      'revision': 1,
	      'inspquestionnum': '1260',
	      '_rowstamp': '[0 0 0 0 0 27 -27 -85]',
	      'orgid': 'EAGLENA',
	      '_id': '1143-1123-1260-EAGLENA-1176-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '1146',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1123',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRklFTERSRVNVTFQvMTE0My8xMTIzLzEyNjAvRUFHTEVOQS8xMTc2LzEvQkVERk9SRA--',
	      'inspfieldresultid_localized': '405'
	    },
	    {
	      'txtresponse': 'Question 2 Response 1',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspfieldresult/1-406',
	      'inspfieldresultid': 406,
	      'entereddate_localized': '3/23/17 8:33 PM',
	      'resultnum': '1176',
	      'inspfieldnum': '1144',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-03-23T20:33:38-04:00',
	      'revision': 1,
	      'inspquestionnum': '1261',
	      '_rowstamp': '[0 0 0 0 0 27 -27 -72]',
	      'orgid': 'EAGLENA',
	      '_id': '1144-1123-1261-EAGLENA-1176-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '1147',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1123',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRklFTERSRVNVTFQvMTE0NC8xMTIzLzEyNjEvRUFHTEVOQS8xMTc2LzEvQkVERk9SRA--',
	      'inspfieldresultid_localized': '406'
	    },
	    {
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspfieldresult/2-407',
	      'inspfieldresultid': 407,
	      'entereddate_localized': '3/23/17 8:33 PM',
	      'resultnum': '1176',
	      'inspfieldnum': '1145',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-03-23T20:33:50-04:00',
	      'revision': 1,
	      'inspquestionnum': '1261',
	      '_rowstamp': '[0 0 0 0 0 27 -27 -27]',
	      'orgid': 'EAGLENA',
	      '_id': '1145-1123-1261-EAGLENA-1176-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '1148',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1123',
	      'numresponse': '100.50',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRklFTERSRVNVTFQvMTE0NS8xMTIzLzEyNjEvRUFHTEVOQS8xMTc2LzEvQkVERk9SRA--',
	      'inspfieldresultid_localized': '407'
	    }
	  ],
	  'revision_localized': '1',
	  'inspformnum': '1123',
	  'siteid': 'BEDFORD',
	  'href': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-',
	  'status_maxvalue': 'INPROG',
	  'inspresultstatus_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspresultstatus',
	  'asset': {
	    'description': 'HVAC System- 50 Ton Cool Cap/ 450000 Btu Heat Cap'
	  },
	  'status': 'INPROG',
	  'inspectionresultid': 438,
	  'inspresultstatus': [
	    {
	      'changedate': '2017-03-23T20:32:56-04:00',
	      'changedate_localized': '3/23/17 8:32 PM',
	      'status_description': 'In Progress',
	      'status': 'INPROG',
	      'changeby': 'ALVIN',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspresultstatus/0-418',
	      '_rowstamp': '[0 0 0 0 0 27 -27 -102]',
	      'inspresultstatusnum': '1060',
	      '_id': '1060-EAGLENA-BEDFORD',
	      'inspresultstatusid': 418,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQUkVTVUxUU1RBVFVTLzEwNjAvRUFHTEVOQS9CRURGT1JE',
	      'inspresultstatusid_localized': '418',
	      'status_maxvalue': 'INPROG'
	    }
	  ],
	  'createdby': 'ALVIN',
	  'inspectionresultid_localized': '438',
	  'referenceobject': 'ASSET',
	  'createdate_localized': '3/23/17 8:32 PM',
	  'inspectionform_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspfieldresult'
	}];

var textfieldwithresponse = [{
	  'hasld_localized': 'N',
	  'showdate_localized': 'N',
	  'langcode': 'EN',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 27 -27 6]',
	  '_id': '1143-1123-1260-EAGLENA-1',
	  'orgid': 'EAGLENA',
	  'showdate': false,
	  'description': 'Text Response #1 Desc:',
	  'inspfieldresult': [
	    {
	      'txtresponse': 'Answer to Question1 Response',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817/inspfieldresult/0-405',
	      'inspfieldresultid': 405,
	      'entereddate_localized': '3/23/17 8:33 PM',
	      'resultnum': '1176',
	      'inspfieldnum': '1143',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-03-23T20:33:20-04:00',
	      'revision': 1,
	      'inspquestionnum': '1260',
	      '_rowstamp': '[0 0 0 0 0 27 -27 -85]',
	      'orgid': 'EAGLENA',
	      '_id': '1143-1123-1260-EAGLENA-1176-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '1146',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1123',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTQzLzExMjMvMTI2MC9FQUdMRU5BLzExNzYvMS9CRURGT1JE',
	      'inspfieldresultid_localized': '405'
	    }
	  ],
	  'revision_localized': '1',
	  'inspformnum': '1123',
	  'showtime': false,
	  'required': false,
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDMvMTEyMy8xMjYwL0VBR0xFTkEvMQ--',
	  'required_localized': 'N',
	  'inspfieldid_localized': '817',
	  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817/inspfieldoption',
	  'fieldtype': 'TR',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817',
	  'showtime_localized': 'N',
	  'inspfieldnum': '1143',
	  'inspquestionnum': '1260',
	  'sequence': 1,
	  'sequence_localized': '1',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/0-911/inspfield/0-817/inspfieldresult',
	  'inspfieldid': 817,
	  'hasld': false
	}];

var numericfieldwithresponse = [{
	  'hasld_localized': 'N',
	  'showdate_localized': 'N',
	  'langcode': 'EN',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 27 -27 84]',
	  '_id': '1145-1123-1261-EAGLENA-1',
	  'orgid': 'EAGLENA',
	  'showdate': false,
	  'description': 'Numeric Response - Question 2',
	  'inspfieldresult': [
	    {
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819/inspfieldresult/0-407',
	      'inspfieldresultid': 407,
	      'entereddate_localized': '3/23/17 8:33 PM',
	      'resultnum': '1176',
	      'inspfieldnum': '1145',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-03-23T20:33:50-04:00',
	      'revision': 1,
	      'inspquestionnum': '1261',
	      '_rowstamp': '[0 0 0 0 0 27 -27 -27]',
	      'orgid': 'EAGLENA',
	      '_id': '1145-1123-1261-EAGLENA-1176-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '1148',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1123',
	      'numresponse': '100.50',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTQ1LzExMjMvMTI2MS9FQUdMRU5BLzExNzYvMS9CRURGT1JE',
	      'inspfieldresultid_localized': '407'
	    }
	  ],
	  'revision_localized': '1',
	  'inspformnum': '1123',
	  'showtime': false,
	  'required': false,
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExNDUvMTEyMy8xMjYxL0VBR0xFTkEvMQ--',
	  'required_localized': 'N',
	  'inspfieldid_localized': '819',
	  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819/inspfieldoption',
	  'fieldtype': 'SE',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819',
	  'showtime_localized': 'N',
	  'inspfieldnum': '1145',
	  'inspquestionnum': '1261',
	  'sequence': 2,
	  'sequence_localized': '2',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTc2L0JFREZPUkQ-/inspectionform/0-913/inspquestion/1-912/inspfield/1-819/inspfieldresult',
	  'inspfieldid': 819,
	  'hasld': false
	}];

var itemfield = [{
	  'hasld_localized': 'N',
	  'showdate_localized': 'N',
	  'inspfieldoption': [
	    {
	      'hasld_localized': 'N',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldoption/0-8374',
	      'inspfieldoptionid': 8374,
	      'inspfieldnum': '3214',
	      'langcode': 'EN',
	      'revision': 1,
	      'inspquestionnum': '2968',
	      '_rowstamp': '[0 0 0 0 0 24 -12 82]',
	      'orgid': 'EAGLENA',
	      '_id': '8374',
	      'sequence': 3,
	      'description': 'MAYBE',
	      'inspfieldoptionid_localized': '8,374',
	      'sequence_localized': '3',
	      'revision_localized': '1',
	      'inspformnum': '1021',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzc0',
	      'hasld': false
	    },
	    {
	      'hasld_localized': 'N',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldoption/1-8373',
	      'inspfieldoptionid': 8373,
	      'inspfieldnum': '3214',
	      'langcode': 'EN',
	      'revision': 1,
	      'inspquestionnum': '2968',
	      '_rowstamp': '[0 0 0 0 0 24 -12 83]',
	      'orgid': 'EAGLENA',
	      '_id': '8373',
	      'sequence': 2,
	      'description': 'NO',
	      'inspfieldoptionid_localized': '8,373',
	      'sequence_localized': '2',
	      'revision_localized': '1',
	      'inspformnum': '1021',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzcz',
	      'hasld': false
	    },
	    {
	      'hasld_localized': 'N',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldoption/2-8372',
	      'inspfieldoptionid': 8372,
	      'inspfieldnum': '3214',
	      'langcode': 'EN',
	      'revision': 1,
	      'inspquestionnum': '2968',
	      '_rowstamp': '[0 0 0 0 0 24 -12 84]',
	      'orgid': 'EAGLENA',
	      '_id': '8372',
	      'sequence': 1,
	      'description': 'YES',
	      'inspfieldoptionid_localized': '8,372',
	      'sequence_localized': '1',
	      'revision_localized': '1',
	      'inspformnum': '1021',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzcy',
	      'hasld': false
	    }
	  ],
	  'langcode': 'EN',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 24 -12 81]',
	  '_id': '3214-1021-2968-EAGLENA-1',
	  'orgid': 'EAGLENA',
	  'showdate': false,
	  'description': 'Single Choice Label - NOT REQUIRED',
	  'revision_localized': '1',
	  'inspformnum': '1021',
	  'showtime': false,
	  'required': false,
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzMyMTQvMTAyMS8yOTY4L0VBR0xFTkEvMQ--',
	  'required_localized': 'N',
	  'inspfieldid_localized': '2,065',
	  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldoption',
	  'fieldtype': 'SO',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065',
	  'showtime_localized': 'N',
	  'inspfieldnum': '3214',
	  'inspquestionnum': '2968',
	  'sequence': 1,
	  'sequence_localized': '1',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldresult',
	  'inspfieldid': 2065,
	  'hasld': false
	}];

var selectResultRecord = [{
	  'status_description': 'In Progress',
	  'createdate': '2017-04-10T10:41:37-04:00',
	  'resultnum': '1046',
	  '$alias_this_attr$asset': '11200',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 24 -12 -93]',
	  'orgid': 'EAGLENA',
	  '_id': 'EAGLENA-1046-BEDFORD',
	  'locations': {},
	  'inspectionform': [
	    {
	      'changedate': '2017-04-10T10:41:11-04:00',
	      'hasld_localized': 'N',
	      'inspectionformid': 311,
	      'status_description': 'Active',
	      'createdate': '2017-04-10T10:39:19-04:00',
	      'hasrevision': false,
	      'langcode': 'EN',
	      'hasrevision_localized': 'N',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 24 -12 100]',
	      '_id': '1021-EAGLENA-1',
	      'name': 'Simple Form',
	      'revision_localized': '1',
	      'inspformnum': '1021',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS8xMDIxL0VBR0xFTkEvMQ--',
	      'status_maxvalue': 'ACTIVE',
	      'inspquestion_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion',
	      'changedate_localized': '4/10/17 10:41 AM',
	      'changeby': 'THEO',
	      'status': 'ACTIVE',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311',
	      'createdby': 'THEO',
	      'inspectionformid_localized': '311',
	      'inspquestion': [
	        {
	          'groupseq_localized': '1.00',
	          'groupseq': 1,
	          'hasld_localized': 'N',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978',
	          'langcode': 'EN',
	          'inspquestionnum': '2968',
	          'inspfield': [
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldoption/0-8374',
	                  'inspfieldoptionid': 8374,
	                  'inspfieldnum': '3214',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 82]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8374',
	                  'sequence': 3,
	                  'description': 'MAYBE',
	                  'inspfieldoptionid_localized': '8,374',
	                  'sequence_localized': '3',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzc0',
	                  'hasld': false
	                },
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldoption/1-8373',
	                  'inspfieldoptionid': 8373,
	                  'inspfieldnum': '3214',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 83]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8373',
	                  'sequence': 2,
	                  'description': 'NO',
	                  'inspfieldoptionid_localized': '8,373',
	                  'sequence_localized': '2',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzcz',
	                  'hasld': false
	                },
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldoption/2-8372',
	                  'inspfieldoptionid': 8372,
	                  'inspfieldnum': '3214',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 84]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8372',
	                  'sequence': 1,
	                  'description': 'YES',
	                  'inspfieldoptionid_localized': '8,372',
	                  'sequence_localized': '1',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzcy',
	                  'hasld': false
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 24 -12 81]',
	              '_id': '3214-1021-2968-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Single Choice Label - NOT REQUIRED',
	              'inspfieldresult': [
	                {
	                  'txtresponse': 'YES',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldresult/0-511',
	                  'inspfieldresultid': 511,
	                  'entereddate_localized': '4/10/17 3:48 PM',
	                  'resultnum': '1046',
	                  'inspfieldnum': '3214',
	                  'enteredby': 'ALVIN',
	                  'entereddate': '2017-04-10T15:48:40-04:00',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 25 81 -58]',
	                  'orgid': 'EAGLENA',
	                  '_id': '3214-1021-2968-EAGLENA-1046-1-BEDFORD',
	                  'revision_localized': '1',
	                  'inspfieldresultnum': '3224',
	                  'siteid': 'BEDFORD',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8zMjE0LzEwMjEvMjk2OC9FQUdMRU5BLzEwNDYvMS9CRURGT1JE',
	                  'inspfieldresultid_localized': '511'
	                }
	              ],
	              'revision_localized': '1',
	              'inspformnum': '1021',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzMyMTQvMTAyMS8yOTY4L0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '2,065',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldoption',
	              'fieldtype': 'SO',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065',
	              'showtime_localized': 'N',
	              'inspfieldnum': '3214',
	              'inspquestionnum': '2968',
	              'sequence': 1,
	              'sequence_localized': '1',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/0-2065/inspfieldresult',
	              'inspfieldid': 2065,
	              'hasld': false
	            },
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/1-2066/inspfieldoption/0-8378',
	                  'inspfieldoptionid': 8378,
	                  'inspfieldnum': '3215',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 85]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8378',
	                  'sequence': 4,
	                  'description': 'NA',
	                  'inspfieldoptionid_localized': '8,378',
	                  'sequence_localized': '4',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzc4',
	                  'hasld': false
	                },
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/1-2066/inspfieldoption/1-8377',
	                  'inspfieldoptionid': 8377,
	                  'inspfieldnum': '3215',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 86]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8377',
	                  'sequence': 3,
	                  'description': 'MAYBE',
	                  'inspfieldoptionid_localized': '8,377',
	                  'sequence_localized': '3',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzc3',
	                  'hasld': false
	                },
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/1-2066/inspfieldoption/2-8376',
	                  'inspfieldoptionid': 8376,
	                  'inspfieldnum': '3215',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 87]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8376',
	                  'sequence': 2,
	                  'description': 'NO',
	                  'inspfieldoptionid_localized': '8,376',
	                  'sequence_localized': '2',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzc2',
	                  'hasld': false
	                },
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/1-2066/inspfieldoption/3-8375',
	                  'inspfieldoptionid': 8375,
	                  'inspfieldnum': '3215',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 88]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8375',
	                  'sequence': 1,
	                  'description': 'YES',
	                  'inspfieldoptionid_localized': '8,375',
	                  'sequence_localized': '1',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzc1',
	                  'hasld': false
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 24 -12 80]',
	              '_id': '3215-1021-2968-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Single Choice Label - REQUIRED',
	              'inspfieldresult': [
	                {
	                  'txtresponse': 'YES',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/1-2066/inspfieldresult/0-512',
	                  'inspfieldresultid': 512,
	                  'entereddate_localized': '4/10/17 3:48 PM',
	                  'resultnum': '1046',
	                  'inspfieldnum': '3215',
	                  'enteredby': 'ALVIN',
	                  'entereddate': '2017-04-10T15:48:42-04:00',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 25 81 -57]',
	                  'orgid': 'EAGLENA',
	                  '_id': '3215-1021-2968-EAGLENA-1046-1-BEDFORD',
	                  'revision_localized': '1',
	                  'inspfieldresultnum': '3225',
	                  'siteid': 'BEDFORD',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8zMjE1LzEwMjEvMjk2OC9FQUdMRU5BLzEwNDYvMS9CRURGT1JE',
	                  'inspfieldresultid_localized': '512'
	                }
	              ],
	              'revision_localized': '1',
	              'inspformnum': '1021',
	              'showtime': false,
	              'required': true,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzMyMTUvMTAyMS8yOTY4L0VBR0xFTkEvMQ--',
	              'required_localized': 'Y',
	              'inspfieldid_localized': '2,066',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/1-2066/inspfieldoption',
	              'fieldtype': 'SO',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/1-2066',
	              'showtime_localized': 'N',
	              'inspfieldnum': '3215',
	              'inspquestionnum': '2968',
	              'sequence': 2,
	              'sequence_localized': '2',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/1-2066/inspfieldresult',
	              'inspfieldid': 2066,
	              'hasld': false
	            },
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/2-2067/inspfieldoption/0-8380',
	                  'inspfieldoptionid': 8380,
	                  'inspfieldnum': '3216',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 89]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8380',
	                  'sequence': 2,
	                  'description': 'NO',
	                  'inspfieldoptionid_localized': '8,380',
	                  'sequence_localized': '2',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzgw',
	                  'hasld': false
	                },
	                {
	                  'hasld_localized': 'N',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/2-2067/inspfieldoption/1-8379',
	                  'inspfieldoptionid': 8379,
	                  'inspfieldnum': '3216',
	                  'langcode': 'EN',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 24 -12 90]',
	                  'orgid': 'EAGLENA',
	                  '_id': '8379',
	                  'sequence': 1,
	                  'description': 'YES',
	                  'inspfieldoptionid_localized': '8,379',
	                  'sequence_localized': '1',
	                  'revision_localized': '1',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi84Mzc5',
	                  'hasld': false
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 24 -12 79]',
	              '_id': '3216-1021-2968-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'inspfieldresult': [
	                {
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/2-2067/inspfieldresult/0-513',
	                  'inspfieldresultid': 513,
	                  'entereddate_localized': '4/10/17 3:35 PM',
	                  'resultnum': '1046',
	                  'inspfieldnum': '3216',
	                  'enteredby': 'ALVIN',
	                  'entereddate': '2017-04-10T15:35:40-04:00',
	                  'revision': 1,
	                  'inspquestionnum': '2968',
	                  '_rowstamp': '[0 0 0 0 0 25 77 -33]',
	                  'orgid': 'EAGLENA',
	                  '_id': '3216-1021-2968-EAGLENA-1046-1-BEDFORD',
	                  'revision_localized': '1',
	                  'inspfieldresultnum': '3226',
	                  'siteid': 'BEDFORD',
	                  'inspformnum': '1021',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8zMjE2LzEwMjEvMjk2OC9FQUdMRU5BLzEwNDYvMS9CRURGT1JE',
	                  'inspfieldresultid_localized': '513'
	                }
	              ],
	              'revision_localized': '1',
	              'inspformnum': '1021',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzMyMTYvMTAyMS8yOTY4L0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '2,067',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/2-2067/inspfieldoption',
	              'fieldtype': 'SO',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/2-2067',
	              'inspfieldnum': '3216',
	              'showtime_localized': 'N',
	              'inspquestionnum': '2968',
	              'sequence': 3,
	              'sequence_localized': '3',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield/2-2067/inspfieldresult',
	              'inspfieldid': 2067,
	              'hasld': false
	            }
	          ],
	          '_rowstamp': '[0 0 0 0 0 24 -12 78]',
	          'inspquestionid_localized': '1,978',
	          '_id': '1021-2968-EAGLENA-1',
	          'sequence': 1,
	          'description': 'What is your Question Test?',
	          'sequence_localized': '1',
	          'inspquestionid': 1978,
	          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform/0-311/inspquestion/0-1978/inspfield',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTAyMS8yOTY4L0VBR0xFTkEvMQ--',
	          'hasld': false,
	          'required': true,
	          '_done': true,
	          'listdesc': '1. What is your Question Test?'
	        }
	      ],
	      'createdate_localized': '4/10/17 10:39 AM',
	      'hasld': false
	    }
	  ],
	  'inspfieldresult': [
	    {
	      'txtresponse': 'YES',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspfieldresult/0-511',
	      'inspfieldresultid': 511,
	      'entereddate_localized': '4/10/17 3:48 PM',
	      'resultnum': '1046',
	      'inspfieldnum': '3214',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-04-10T15:48:40-04:00',
	      'revision': 1,
	      'inspquestionnum': '2968',
	      '_rowstamp': '[0 0 0 0 0 25 81 -58]',
	      'orgid': 'EAGLENA',
	      '_id': '3214-1021-2968-EAGLENA-1046-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '3224',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1021',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRklFTERSRVNVTFQvMzIxNC8xMDIxLzI5NjgvRUFHTEVOQS8xMDQ2LzEvQkVERk9SRA--',
	      'inspfieldresultid_localized': '511'
	    },
	    {
	      'txtresponse': 'YES',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspfieldresult/1-512',
	      'inspfieldresultid': 512,
	      'entereddate_localized': '4/10/17 3:48 PM',
	      'resultnum': '1046',
	      'inspfieldnum': '3215',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-04-10T15:48:42-04:00',
	      'revision': 1,
	      'inspquestionnum': '2968',
	      '_rowstamp': '[0 0 0 0 0 25 81 -57]',
	      'orgid': 'EAGLENA',
	      '_id': '3215-1021-2968-EAGLENA-1046-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '3225',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1021',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRklFTERSRVNVTFQvMzIxNS8xMDIxLzI5NjgvRUFHTEVOQS8xMDQ2LzEvQkVERk9SRA--',
	      'inspfieldresultid_localized': '512'
	    },
	    {
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspfieldresult/2-513',
	      'inspfieldresultid': 513,
	      'entereddate_localized': '4/10/17 3:35 PM',
	      'resultnum': '1046',
	      'inspfieldnum': '3216',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-04-10T15:35:40-04:00',
	      'revision': 1,
	      'inspquestionnum': '2968',
	      '_rowstamp': '[0 0 0 0 0 25 77 -33]',
	      'orgid': 'EAGLENA',
	      '_id': '3216-1021-2968-EAGLENA-1046-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '3226',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1021',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRklFTERSRVNVTFQvMzIxNi8xMDIxLzI5NjgvRUFHTEVOQS8xMDQ2LzEvQkVERk9SRA--',
	      'inspfieldresultid_localized': '513'
	    }
	  ],
	  'revision_localized': '1',
	  'inspformnum': '1021',
	  'siteid': 'BEDFORD',
	  'href': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-',
	  'status_maxvalue': 'INPROG',
	  'inspresultstatus_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspresultstatus',
	  'asset': {
	    'description': 'HVAC System- 50 Ton Cool Cap/ 450000 Btu Heat Cap'
	  },
	  'status': 'INPROG',
	  'inspectionresultid': 504,
	  'inspresultstatus': [
	    {
	      'changedate': '2017-04-10T10:41:37-04:00',
	      'changedate_localized': '4/10/17 10:41 AM',
	      'status_description': 'In Progress',
	      'status': 'INPROG',
	      'changeby': 'ALVIN',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspresultstatus/0-502',
	      '_rowstamp': '[0 0 0 0 0 24 -12 -92]',
	      'inspresultstatusnum': '1052',
	      '_id': '1052-EAGLENA-BEDFORD',
	      'inspresultstatusid': 502,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQUkVTVUxUU1RBVFVTLzEwNTIvRUFHTEVOQS9CRURGT1JE',
	      'inspresultstatusid_localized': '502',
	      'status_maxvalue': 'INPROG'
	    }
	  ],
	  'createdby': 'ALVIN',
	  'inspectionresultid_localized': '504',
	  'referenceobject': 'ASSET',
	  'createdate_localized': '4/10/17 10:41 AM',
	  'inspectionform_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspectionform',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMDQ2L0JFREZPUkQ-/inspfieldresult'
	}];


