/*
 * Licensed Materials - Property of IBM
 *
 * 5724-U18
 *
 * (C) Copyright IBM Corp. 2017 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with
 * IBM Corp.
 */

var mockEvent = document.createEvent('Event');
var mockDupEvent = document.createEvent('Event');
var mockEditEvent = document.createEvent('Event');
mockEvent.detail = {'inspectionformstatus_collectionref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/inspectionformstatus','status_description':'Inactive','createdate':'2017-01-26T13:16:12-05:00','orgid':'EAGLENA','originalformnum':0,'revision':1,'langcode':'EN','inspectionformid':504,'isrevision':false,'hasld':false,'hasrevision':false,'href':'http://localhost:7001/maximo/oslc/os/mxapiinspform','inspquestion_collectionref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/inspquestion','status':'INACTIVE'}
mockDupEvent.detail = {'changedate':'2017-01-30T16:50:31-05:00','inspquestion_collectionref':'http:\/\/localhost:7001\/maximo\/oslc\/os\/mxapiinspform\/_MTAwMS9FQUdMRU5BLzE-\/inspquestion','inspectionformid':61,'status_description':'Inactive','status':'INACTIVE','changeby':'THEO','createdate':'2017-01-30T16:50:31-05:00','hasrevision':false,'createdby':'THEO','langcode':'EN','inspectionformstatus_collectionref':'http:\/\/localhost:7001\/maximo\/oslc\/os\/mxapiinspform\/_MTAwMS9FQUdMRU5BLzE-\/inspectionformstatus','revision':1,'orgid':'EAGLENA','isrevision':false,'siteid':'BEDFORD','inspformnum':'1004','href':'http:\/\/localhost:7001\/maximo\/oslc\/os\/mxapiinspform\/_MTAwMS9FQUdMRU5BLzE-','hasld':false}
var mockFormStatusSet = [{'_rowstamp':'[0 0 0 0 0 30 -68 117]','synonymdomainid':16011,'valueid':'INSPECTFORMSTATUS|ACTIVE','maxvalue':'ACTIVE','localref':'http://localhost:7001/maximo/oslc/os/mxdomain/_SU5TUEVDVEZPUk1TVEFUVVM-/synonymdomain/0-16011','defaults':true,'defaults_localized':'Y','description':'Active','synonymdomainid_localized':'16,011','href':'http://localhost:7001/maximo/oslc/os/mxdomain/_SU5TUEVDVEZPUk1TVEFUVVM-#TUF…9OWU1ET01BSU4vSU5TUEVDVEZPUk1TVEFUVVMvQUNUSVZFL35OVUxMfi9_TlVMTH4vQUNUSVZF','_id':'INSPECTFORMSTATUS-ACTIVE-~NULL~-~NULL~-ACTIVE','value':'ACTIVE'},{'_rowstamp':'[0 0 0 0 0 30 -68 118]','synonymdomainid':16012,'valueid':'INSPECTFORMSTATUS|INACTIVE','maxvalue':'INACTIVE','localref':'http://localhost:7001/maximo/oslc/os/mxdomain/_SU5TUEVDVEZPUk1TVEFUVVM-/synonymdomain/1-16012','defaults':true,'defaults_localized':'Y','description':'Inactive','synonymdomainid_localized':'16,012','href':'http://localhost:7001/maximo/oslc/os/mxdomain/_SU5TUEVDVEZPUk1TVEFUVVM-#TUF…1BSU4vSU5TUEVDVEZPUk1TVEFUVVMvSU5BQ1RJVkUvfk5VTEx_L35OVUxMfi9JTkFDVElWRQ--','_id':'INSPECTFORMSTATUS-INACTIVE-~NULL~-~NULL~-INACTIVE','value':'INACTIVE'},{'_rowstamp':'[0 0 0 0 0 30 -68 120]','synonymdomainid':16014,'valueid':'INSPECTFORMSTATUS|PNDREV','maxvalue':'PNDREV','localref':'http://localhost:7001/maximo/oslc/os/mxdomain/_SU5TUEVDVEZPUk1TVEFUVVM-/synonymdomain/2-16014','defaults':true,'defaults_localized':'Y','description':'Inactive Revision','synonymdomainid_localized':'16,014','href':'http://localhost:7001/maximo/oslc/os/mxdomain/_SU5TUEVDVEZPUk1TVEFUVVM-#TUF…9OWU1ET01BSU4vSU5TUEVDVEZPUk1TVEFUVVMvUE5EUkVWL35OVUxMfi9_TlVMTH4vUE5EUkVW','_id':'INSPECTFORMSTATUS-PNDREV-~NULL~-~NULL~-PNDREV','value':'PNDREV'},{'_rowstamp':'[0 0 0 0 0 30 -68 119]','synonymdomainid':16013,'valueid':'INSPECTFORMSTATUS|REVISED','maxvalue':'REVISED','localref':'http://localhost:7001/maximo/oslc/os/mxdomain/_SU5TUEVDVEZPUk1TVEFUVVM-/synonymdomain/3-16013','defaults':true,'defaults_localized':'Y','description':'Revised','synonymdomainid_localized':'16,013','href':'http://localhost:7001/maximo/oslc/os/mxdomain/_SU5TUEVDVEZPUk1TVEFUVVM-#TUF…1ET01BSU4vSU5TUEVDVEZPUk1TVEFUVVMvUkVWSVNFRC9_TlVMTH4vfk5VTEx_L1JFVklTRUQ-','_id':'INSPECTFORMSTATUS-REVISED-~NULL~-~NULL~-REVISED','value':'REVISED'}];
mockEditEvent.detail = {'changedate':'2017-02-15T16:04:09-05:00','hasld_localized':'N','inspectionformid':2,'status_description':'ACTIVE','isrevision_localized':'N','createdate':'2017-02-15T16:04:09-05:00','hasrevision':false,'langcode':'EN','hasrevision_localized':'N','inspectionformstatus_collectionref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/_MTAwMS9FQUdMRU5BLzE-/inspectionformstatus','revision':1,'_rowstamp':'1144958','_id':'1001-EAGLENA-1','orgid':'EAGLENA','name':'Test Form One','isrevision':false,'revision_localized':'1','inspformnum':'1001','siteid':'BEDFORD','inspectionformstatus':[{'changedate':'2017-02-15T16:04:09-05:00','changedate_localized':'2/15/17 4:04 PM','status_description':'ACTIVE','status':'ACTIVE','changeby':'THEO','localref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/_MTAwMS9FQUdMRU5BLzE-/inspectionformstatus/0-1','inspectionformstatusid':1,'_rowstamp':'1144959','_id':'1','name':'TEST FORM ONE','inspectionformstatusid_localized':'1','siteid':'BEDFORD','href':'http://childkey#SU5TUEVDVElPTkZPUk0vSU5TUEVDVElPTkZPUk1TVEFUVVMvMQ--','status_maxvalue':'ACTIVE'}],'personcreate':{'displayname':'Theodore Seville'},'status_maxvalue':'ACTIVE','href':'http://localhost:7001/maximo/oslc/os/mxapiinspform/_MTAwMS9FQUdMRU5BLzE-','personchange':{'displayname':'Theodore Seville'},'inspquestion_collectionref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/_MTAwMS9FQUdMRU5BLzE-/inspquestion','changedate_localized':'2/15/17 4:04 PM','status':'ACTIVE','changeby':'THEO','createdby':'THEO','inspectionformid_localized':'2','inspquestion':[{'hasld_localized':'N','localref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/_MTAwMS9FQUdMRU5BLzE-/inspquestion/0-1','langcode':'EN','inspquestionnum':'1001','_rowstamp':'1145109','inspquestionid_localized':'1','_id':'1001-1001-EAGLENA-1','sequence':0,'description':'Does anyone really know what time it is?','sequence_localized':'0.00','inspquestionid':1,'inspfield_collectionref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/_MTAwMS9FQUdMRU5BLzE-/inspquestion/0-1/inspfield','required':false,'href':'http://childkey#SU5TUEVDVElPTkZPUk0vSU5TUFFVRVNUSU9OLzEwMDEvMTAwMS9FQUdMRU5BLzE-','required_localized':'N','hasld':false},{'hasld_localized':'N','localref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/_MTAwMS9FQUdMRU5BLzE-/inspquestion/1-2','langcode':'EN','inspquestionnum':'1002','_rowstamp':'1145119','inspquestionid_localized':'2','_id':'1001-1002-EAGLENA-1','sequence':0,'description':'Does anyone really care?','sequence_localized':'0.00','inspquestionid':2,'inspfield_collectionref':'http://localhost:7001/maximo/oslc/os/mxapiinspform/_MTAwMS9FQUdMRU5BLzE-/inspquestion/1-2/inspfield','required':false,'href':'http://childkey#SU5TUEVDVElPTkZPUk0vSU5TUFFVRVNUSU9OLzEwMDEvMTAwMi9FQUdMRU5BLzE-','required_localized':'N','hasld':false}],'createdate_localized':'2/15/17 4:04 PM','hasld':false};
