/*
 * Licensed Materials - Property of IBM
 *
 * 5724-U18
 *
 * (C) Copyright IBM Corp. 2017 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with
 * IBM Corp.
 */

var resultRecord = [{
	  'status_description': 'In Progress',
	  'createdate': '2017-03-23T22:32:48-04:00',
	  'resultnum': '1184',
	  '$alias_this_attr$asset': '11450',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 28 8 -35]',
	  'orgid': 'EAGLENA',
	  '_id': 'EAGLENA-1184-BEDFORD',
	  'locations': {},
	  'inspectionform': [
	    {
	      'changedate': '2017-03-23T22:32:24-04:00',
	      'hasld_localized': 'N',
	      'inspectionformid': 921,
	      'status_description': 'Active',
	      'createdate': '2017-03-23T22:31:30-04:00',
	      'hasrevision': false,
	      'langcode': 'EN',
	      'hasrevision_localized': 'N',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 28 8 -61]',
	      '_id': '1127-EAGLENA-1',
	      'name': 'Simple Group',
	      'revision_localized': '1',
	      'inspformnum': '1127',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS8xMTI3L0VBR0xFTkEvMQ--',
	      'status_maxvalue': 'ACTIVE',
	      'inspquestion_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion',
	      'changedate_localized': '3/23/17 10:32 PM',
	      'changeby': 'THEO',
	      'status': 'ACTIVE',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921',
	      'createdby': 'THEO',
	      'inspectionformid_localized': '921',
	      'inspquestion': [
	        {
	          'groupseq_localized': '1.10',
	          'groupseq': 1.1,
	          'hasld_localized': 'N',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942',
	          'langcode': 'EN',
	          'inspquestionnum': '1302',
	          'inspfield': [
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  '_rowstamp': '[0 0 0 0 0 28 8 -80]',
	                  '_id': '94',
	                  'sequence': 2,
	                  'description': 'example 2',
	                  'inspfieldoptionid_localized': '94',
	                  'sequence_localized': '2',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/0-94',
	                  'inspfieldoptionid': 94,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NA--'
	                },
	                {
	                  '_rowstamp': '[0 0 0 0 0 28 8 -79]',
	                  '_id': '93',
	                  'sequence': 1,
	                  'description': 'example 1',
	                  'inspfieldoptionid_localized': '93',
	                  'sequence_localized': '1',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/1-93',
	                  'inspfieldoptionid': 93,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Mw--'
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 28 8 -81]',
	              '_id': '1193-1127-1302-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Response #1:',
	              'revision_localized': '1',
	              'inspformnum': '1127',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTMvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '846',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption',
	              'fieldtype': 'TR',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846',
	              'showtime_localized': 'N',
	              'inspfieldnum': '1193',
	              'inspquestionnum': '1302',
	              'sequence': 1,
	              'sequence_localized': '1',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldresult',
	              'inspfieldid': 846,
	              'hasld': false
	            },
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  '_rowstamp': '[0 0 0 0 0 28 8 -78]',
	                  '_id': '96',
	                  'sequence': 2,
	                  'description': 'example 2',
	                  'inspfieldoptionid_localized': '96',
	                  'sequence_localized': '2',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/0-96',
	                  'inspfieldoptionid': 96,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Ng--'
	                },
	                {
	                  '_rowstamp': '[0 0 0 0 0 28 8 -77]',
	                  '_id': '95',
	                  'sequence': 1,
	                  'description': 'example 1',
	                  'inspfieldoptionid_localized': '95',
	                  'sequence_localized': '1',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/1-95',
	                  'inspfieldoptionid': 95,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NQ--'
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 28 8 -82]',
	              '_id': '1194-1127-1302-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Response #2:',
	              'inspfieldresult': [
	                {
	                  'txtresponse': 'Data entered',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult/0-416',
	                  'inspfieldresultid': 416,
	                  'entereddate_localized': '3/23/17 10:38 PM',
	                  'resultnum': '1184',
	                  'inspfieldnum': '1194',
	                  'enteredby': 'ALVIN',
	                  'entereddate': '2017-03-23T22:38:59-04:00',
	                  'revision': 1,
	                  'inspquestionnum': '1302',
	                  '_rowstamp': '[0 0 0 0 0 28 10 -61]',
	                  'orgid': 'EAGLENA',
	                  '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
	                  'revision_localized': '1',
	                  'inspfieldresultnum': '1195',
	                  'siteid': 'BEDFORD',
	                  'inspformnum': '1127',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTk0LzExMjcvMTMwMi9FQUdMRU5BLzExODQvMS9CRURGT1JE',
	                  'inspfieldresultid_localized': '416'
	                }
	              ],
	              'revision_localized': '1',
	              'inspformnum': '1127',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTQvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '847',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption',
	              'fieldtype': 'TR',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847',
	              'showtime_localized': 'N',
	              'inspfieldnum': '1194',
	              'inspquestionnum': '1302',
	              'sequence': 2,
	              'sequence_localized': '2',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult',
	              'inspfieldid': 847,
	              'hasld': false
	            }
	          ],
	          'inspquestionid_localized': '942',
	          '_rowstamp': '[0 0 0 0 0 28 8 -70]',
	          '_id': '1127-1302-EAGLENA-1',
	          'sequence': 1,
	          'description': 'Question #1',
	          'groupid_localized': '1',
	          'sequence_localized': '1',
	          'inspquestionid': 942,
	          'groupid': 1,
	          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	          'hasld': false
	        },
	        {
	          'groupseq_localized': '1.00',
	          'groupseq': 1,
	          'hasld_localized': 'N',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/1-943',
	          'langcode': 'EN',
	          'inspquestionnum': '1303',
	          'inspquestionid_localized': '943',
	          '_rowstamp': '[0 0 0 0 0 28 8 -66]',
	          '_id': '1127-1303-EAGLENA-1',
	          'sequence': 0,
	          'description': 'Group A',
	          'groupid_localized': '1',
	          'sequence_localized': '0',
	          'inspquestionid': 943,
	          'groupid': 1,
	          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/1-943/inspfield',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAzL0VBR0xFTkEvMQ--',
	          'hasld': false
	        }
	      ],
	      'createdate_localized': '3/23/17 10:31 PM',
	      'hasld': false
	    }
	  ],
	  'inspfieldresult': [
	    {
	      'txtresponse': 'Data entered',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspfieldresult/0-416',
	      'inspfieldresultid': 416,
	      'entereddate_localized': '3/23/17 10:38 PM',
	      'resultnum': '1184',
	      'inspfieldnum': '1194',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-03-23T22:38:59-04:00',
	      'revision': 1,
	      'inspquestionnum': '1302',
	      '_rowstamp': '[0 0 0 0 0 28 10 -61]',
	      'orgid': 'EAGLENA',
	      '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '1195',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1127',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRklFTERSRVNVTFQvMTE5NC8xMTI3LzEzMDIvRUFHTEVOQS8xMTg0LzEvQkVERk9SRA--',
	      'inspfieldresultid_localized': '416'
	    }
	  ],
	  'revision_localized': '1',
	  'inspformnum': '1127',
	  'siteid': 'BEDFORD',
	  'href': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-',
	  'status_maxvalue': 'INPROG',
	  'inspresultstatus_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspresultstatus',
	  'asset': {
	    'description': 'Centrifugal Pump 100GPM/60FTHD'
	  },
	  'status': 'INPROG',
	  'inspectionresultid': 446,
	  'inspresultstatus': [
	    {
	      'changedate': '2017-03-23T22:32:48-04:00',
	      'changedate_localized': '3/23/17 10:32 PM',
	      'status_description': 'In Progress',
	      'status': 'INPROG',
	      'changeby': 'ALVIN',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspresultstatus/0-422',
	      '_rowstamp': '[0 0 0 0 0 28 8 -34]',
	      'inspresultstatusnum': '1064',
	      '_id': '1064-EAGLENA-BEDFORD',
	      'inspresultstatusid': 422,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQUkVTVUxUU1RBVFVTLzEwNjQvRUFHTEVOQS9CRURGT1JE',
	      'inspresultstatusid_localized': '422',
	      'status_maxvalue': 'INPROG'
	    }
	  ],
	  'createdby': 'ALVIN',
	  'inspectionresultid_localized': '446',
	  'referenceobject': 'ASSET',
	  'createdate_localized': '3/23/17 10:32 PM',
	  'inspectionform_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspfieldresult'
	}];

var resultRecordNoResponses = [{
	  'status_description': 'In Progress',
	  'createdate': '2017-03-23T22:32:48-04:00',
	  'resultnum': '1184',
	  '$alias_this_attr$asset': '11450',
	  'revision': 1,
	  '_rowstamp': '[0 0 0 0 0 28 8 -35]',
	  'orgid': 'EAGLENA',
	  '_id': 'EAGLENA-1184-BEDFORD',
	  'locations': {},
	  'inspectionform': [
	    {
	      'changedate': '2017-03-23T22:32:24-04:00',
	      'hasld_localized': 'N',
	      'inspectionformid': 921,
	      'status_description': 'Active',
	      'createdate': '2017-03-23T22:31:30-04:00',
	      'hasrevision': false,
	      'langcode': 'EN',
	      'hasrevision_localized': 'N',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 28 8 -61]',
	      '_id': '1127-EAGLENA-1',
	      'name': 'Simple Group',
	      'revision_localized': '1',
	      'inspformnum': '1127',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS8xMTI3L0VBR0xFTkEvMQ--',
	      'status_maxvalue': 'ACTIVE',
	      'inspquestion_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion',
	      'changedate_localized': '3/23/17 10:32 PM',
	      'changeby': 'THEO',
	      'status': 'ACTIVE',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921',
	      'createdby': 'THEO',
	      'inspectionformid_localized': '921',
	      'inspquestion': [
	        {
	          'groupseq_localized': '1.00',
	          'groupseq': 1,
	          'hasld_localized': 'N',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/1-943',
	          'langcode': 'EN',
	          'inspquestionnum': '1303',
	          'inspquestionid_localized': '943',
	          '_rowstamp': '[0 0 0 0 0 28 8 -66]',
	          '_id': '1127-1303-EAGLENA-1',
	          'sequence': 0,
	          'description': 'Group A',
	          'groupid_localized': '1',
	          'sequence_localized': '0',
	          'inspquestionid': 943,
	          'groupid': 1,
	          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/1-943/inspfield',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAzL0VBR0xFTkEvMQ--',
	          'hasld': false,
	          '_done': false,
	          'listdesc': '1. Group A',
	          'children': [
	            {
	              'groupseq_localized': '1.10',
	              'groupseq': 1.1,
	              'hasld_localized': 'N',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942',
	              'langcode': 'EN',
	              'inspquestionnum': '1302',
	              'inspfield': [
	                {
	                  'hasld_localized': 'N',
	                  'showdate_localized': 'N',
	                  'inspfieldoption': [
	                    {
	                      '_rowstamp': '[0 0 0 0 0 28 8 -80]',
	                      '_id': '94',
	                      'sequence': 2,
	                      'description': 'example 2',
	                      'inspfieldoptionid_localized': '94',
	                      'sequence_localized': '2',
	                      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/0-94',
	                      'inspfieldoptionid': 94,
	                      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NA--'
	                    },
	                    {
	                      '_rowstamp': '[0 0 0 0 0 28 8 -79]',
	                      '_id': '93',
	                      'sequence': 1,
	                      'description': 'example 1',
	                      'inspfieldoptionid_localized': '93',
	                      'sequence_localized': '1',
	                      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/1-93',
	                      'inspfieldoptionid': 93,
	                      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Mw--'
	                    }
	                  ],
	                  'langcode': 'EN',
	                  'revision': 1,
	                  '_rowstamp': '[0 0 0 0 0 28 8 -81]',
	                  '_id': '1193-1127-1302-EAGLENA-1',
	                  'orgid': 'EAGLENA',
	                  'showdate': false,
	                  'description': 'Response #1:',
	                  'revision_localized': '1',
	                  'inspformnum': '1127',
	                  'showtime': false,
	                  'required': false,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTMvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	                  'required_localized': 'N',
	                  'inspfieldid_localized': '846',
	                  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption',
	                  'fieldtype': 'TR',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846',
	                  'showtime_localized': 'N',
	                  'inspfieldnum': '1193',
	                  'inspquestionnum': '1302',
	                  'sequence': 1,
	                  'sequence_localized': '1',
	                  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldresult',
	                  'inspfieldid': 846,
	                  'hasld': false
	                },
	                {
	                  'hasld_localized': 'N',
	                  'showdate_localized': 'N',
	                  'inspfieldoption': [
	                    {
	                      '_rowstamp': '[0 0 0 0 0 28 8 -78]',
	                      '_id': '96',
	                      'sequence': 2,
	                      'description': 'example 2',
	                      'inspfieldoptionid_localized': '96',
	                      'sequence_localized': '2',
	                      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/0-96',
	                      'inspfieldoptionid': 96,
	                      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Ng--'
	                    },
	                    {
	                      '_rowstamp': '[0 0 0 0 0 28 8 -77]',
	                      '_id': '95',
	                      'sequence': 1,
	                      'description': 'example 1',
	                      'inspfieldoptionid_localized': '95',
	                      'sequence_localized': '1',
	                      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/1-95',
	                      'inspfieldoptionid': 95,
	                      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NQ--'
	                    }
	                  ],
	                  'langcode': 'EN',
	                  'revision': 1,
	                  '_rowstamp': '[0 0 0 0 0 28 8 -82]',
	                  '_id': '1194-1127-1302-EAGLENA-1',
	                  'orgid': 'EAGLENA',
	                  'showdate': false,
	                  'description': 'Response #2:',
	                  'inspfieldresult': [
	                    {
	                      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult/0-416',
	                      'inspfieldresultid': 416,
	                      'entereddate_localized': '3/23/17 11:39 PM',
	                      'resultnum': '1184',
	                      'inspfieldnum': '1194',
	                      'enteredby': 'ALVIN',
	                      'entereddate': '2017-03-23T23:39:01-04:00',
	                      'revision': 1,
	                      'inspquestionnum': '1302',
	                      '_rowstamp': '[0 0 0 0 0 28 27 -49]',
	                      'orgid': 'EAGLENA',
	                      '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
	                      'revision_localized': '1',
	                      'inspfieldresultnum': '1195',
	                      'siteid': 'BEDFORD',
	                      'inspformnum': '1127',
	                      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTk0LzExMjcvMTMwMi9FQUdMRU5BLzExODQvMS9CRURGT1JE',
	                      'inspfieldresultid_localized': '416'
	                    }
	                  ],
	                  'revision_localized': '1',
	                  'inspformnum': '1127',
	                  'showtime': false,
	                  'required': false,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTQvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	                  'required_localized': 'N',
	                  'inspfieldid_localized': '847',
	                  'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption',
	                  'fieldtype': 'TR',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847',
	                  'showtime_localized': 'N',
	                  'inspfieldnum': '1194',
	                  'inspquestionnum': '1302',
	                  'sequence': 2,
	                  'sequence_localized': '2',
	                  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult',
	                  'inspfieldid': 847,
	                  'hasld': false
	                }
	              ],
	              'inspquestionid_localized': '942',
	              '_rowstamp': '[0 0 0 0 0 28 8 -70]',
	              '_id': '1127-1302-EAGLENA-1',
	              'sequence': 1,
	              'description': 'Question #1',
	              'groupid_localized': '1',
	              'sequence_localized': '1',
	              'inspquestionid': 942,
	              'groupid': 1,
	              'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield',
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	              'hasld': false,
	              '_done': false,
	              'listdesc': '1.1. Question #1'
	            }
	          ]
	        },
	        {
	          'groupseq_localized': '1.10',
	          'groupseq': 1.1,
	          'hasld_localized': 'N',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942',
	          'langcode': 'EN',
	          'inspquestionnum': '1302',
	          'inspfield': [
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  '_rowstamp': '[0 0 0 0 0 28 8 -80]',
	                  '_id': '94',
	                  'sequence': 2,
	                  'description': 'example 2',
	                  'inspfieldoptionid_localized': '94',
	                  'sequence_localized': '2',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/0-94',
	                  'inspfieldoptionid': 94,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NA--'
	                },
	                {
	                  '_rowstamp': '[0 0 0 0 0 28 8 -79]',
	                  '_id': '93',
	                  'sequence': 1,
	                  'description': 'example 1',
	                  'inspfieldoptionid_localized': '93',
	                  'sequence_localized': '1',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/1-93',
	                  'inspfieldoptionid': 93,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Mw--'
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 28 8 -81]',
	              '_id': '1193-1127-1302-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Response #1:',
	              'revision_localized': '1',
	              'inspformnum': '1127',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTMvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '846',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption',
	              'fieldtype': 'TR',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846',
	              'showtime_localized': 'N',
	              'inspfieldnum': '1193',
	              'inspquestionnum': '1302',
	              'sequence': 1,
	              'sequence_localized': '1',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldresult',
	              'inspfieldid': 846,
	              'hasld': false
	            },
	            {
	              'hasld_localized': 'N',
	              'showdate_localized': 'N',
	              'inspfieldoption': [
	                {
	                  '_rowstamp': '[0 0 0 0 0 28 8 -78]',
	                  '_id': '96',
	                  'sequence': 2,
	                  'description': 'example 2',
	                  'inspfieldoptionid_localized': '96',
	                  'sequence_localized': '2',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/0-96',
	                  'inspfieldoptionid': 96,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Ng--'
	                },
	                {
	                  '_rowstamp': '[0 0 0 0 0 28 8 -77]',
	                  '_id': '95',
	                  'sequence': 1,
	                  'description': 'example 1',
	                  'inspfieldoptionid_localized': '95',
	                  'sequence_localized': '1',
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/1-95',
	                  'inspfieldoptionid': 95,
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NQ--'
	                }
	              ],
	              'langcode': 'EN',
	              'revision': 1,
	              '_rowstamp': '[0 0 0 0 0 28 8 -82]',
	              '_id': '1194-1127-1302-EAGLENA-1',
	              'orgid': 'EAGLENA',
	              'showdate': false,
	              'description': 'Response #2:',
	              'inspfieldresult': [
	                {
	                  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult/0-416',
	                  'inspfieldresultid': 416,
	                  'entereddate_localized': '3/23/17 11:39 PM',
	                  'resultnum': '1184',
	                  'inspfieldnum': '1194',
	                  'enteredby': 'ALVIN',
	                  'entereddate': '2017-03-23T23:39:01-04:00',
	                  'revision': 1,
	                  'inspquestionnum': '1302',
	                  '_rowstamp': '[0 0 0 0 0 28 27 -49]',
	                  'orgid': 'EAGLENA',
	                  '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
	                  'revision_localized': '1',
	                  'inspfieldresultnum': '1195',
	                  'siteid': 'BEDFORD',
	                  'inspformnum': '1127',
	                  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTk0LzExMjcvMTMwMi9FQUdMRU5BLzExODQvMS9CRURGT1JE',
	                  'inspfieldresultid_localized': '416'
	                }
	              ],
	              'revision_localized': '1',
	              'inspformnum': '1127',
	              'showtime': false,
	              'required': false,
	              'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTQvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	              'required_localized': 'N',
	              'inspfieldid_localized': '847',
	              'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption',
	              'fieldtype': 'TR',
	              'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847',
	              'showtime_localized': 'N',
	              'inspfieldnum': '1194',
	              'inspquestionnum': '1302',
	              'sequence': 2,
	              'sequence_localized': '2',
	              'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult',
	              'inspfieldid': 847,
	              'hasld': false
	            }
	          ],
	          'inspquestionid_localized': '942',
	          '_rowstamp': '[0 0 0 0 0 28 8 -70]',
	          '_id': '1127-1302-EAGLENA-1',
	          'sequence': 1,
	          'description': 'Question #1',
	          'groupid_localized': '1',
	          'sequence_localized': '1',
	          'inspquestionid': 942,
	          'groupid': 1,
	          'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	          'hasld': false,
	          '_done': false,
	          'listdesc': '1.1. Question #1'
	        }
	      ],
	      'createdate_localized': '3/23/17 10:31 PM',
	      'hasld': false
	    }
	  ],
	  'inspfieldresult': [
	    {
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspfieldresult/0-416',
	      'inspfieldresultid': 416,
	      'entereddate_localized': '3/23/17 11:39 PM',
	      'resultnum': '1184',
	      'inspfieldnum': '1194',
	      'enteredby': 'ALVIN',
	      'entereddate': '2017-03-23T23:39:01-04:00',
	      'revision': 1,
	      'inspquestionnum': '1302',
	      '_rowstamp': '[0 0 0 0 0 28 27 -49]',
	      'orgid': 'EAGLENA',
	      '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
	      'revision_localized': '1',
	      'inspfieldresultnum': '1195',
	      'siteid': 'BEDFORD',
	      'inspformnum': '1127',
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRklFTERSRVNVTFQvMTE5NC8xMTI3LzEzMDIvRUFHTEVOQS8xMTg0LzEvQkVERk9SRA--',
	      'inspfieldresultid_localized': '416'
	    }
	  ],
	  'revision_localized': '1',
	  'inspformnum': '1127',
	  'siteid': 'BEDFORD',
	  'href': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-',
	  'status_maxvalue': 'INPROG',
	  'inspresultstatus_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspresultstatus',
	  'asset': {
	    'description': 'Centrifugal Pump 100GPM/60FTHD'
	  },
	  'status': 'INPROG',
	  'inspectionresultid': 446,
	  'inspresultstatus': [
	    {
	      'changedate': '2017-03-23T22:32:48-04:00',
	      'changedate_localized': '3/23/17 10:32 PM',
	      'status_description': 'In Progress',
	      'status': 'INPROG',
	      'changeby': 'ALVIN',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspresultstatus/0-422',
	      '_rowstamp': '[0 0 0 0 0 28 8 -34]',
	      'inspresultstatusnum': '1064',
	      '_id': '1064-EAGLENA-BEDFORD',
	      'inspresultstatusid': 422,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQUkVTVUxUU1RBVFVTLzEwNjQvRUFHTEVOQS9CRURGT1JE',
	      'inspresultstatusid_localized': '422',
	      'status_maxvalue': 'INPROG'
	    }
	  ],
	  'createdby': 'ALVIN',
	  'inspectionresultid_localized': '446',
	  'referenceobject': 'ASSET',
	  'createdate_localized': '3/23/17 10:32 PM',
	  'inspectionform_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform',
	  'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspfieldresult'
	}];

var questionSet = [[
                    {
                        'groupseq_localized': '1.00',
                        'groupseq': 1,
                        'hasld_localized': 'N',
                        'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/1-943',
                        'langcode': 'EN',
                        'inspquestionnum': '1303',
                        'inspquestionid_localized': '943',
                        '_rowstamp': '[0 0 0 0 0 28 8 -66]',
                        '_id': '1127-1303-EAGLENA-1',
                        'sequence': 0,
                        'description': 'Group A',
                        'groupid_localized': '1',
                        'sequence_localized': '0',
                        'inspquestionid': 943,
                        'groupid': 1,
                        'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/1-943/inspfield',
                        'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAzL0VBR0xFTkEvMQ--',
                        'hasld': false
                      },
                      {
                        'groupseq_localized': '1.10',
                        'groupseq': 1.1,
                        'hasld_localized': 'N',
                        'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942',
                        'langcode': 'EN',
                        'inspquestionnum': '1302',
                        'inspfield': [
                          {
                            'hasld_localized': 'N',
                            'showdate_localized': 'N',
                            'inspfieldoption': [
                              {
                                '_rowstamp': '[0 0 0 0 0 28 8 -80]',
                                '_id': '94',
                                'sequence': 2,
                                'description': 'example 2',
                                'inspfieldoptionid_localized': '94',
                                'sequence_localized': '2',
                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/0-94',
                                'inspfieldoptionid': 94,
                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NA--'
                              },
                              {
                                '_rowstamp': '[0 0 0 0 0 28 8 -79]',
                                '_id': '93',
                                'sequence': 1,
                                'description': 'example 1',
                                'inspfieldoptionid_localized': '93',
                                'sequence_localized': '1',
                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/1-93',
                                'inspfieldoptionid': 93,
                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Mw--'
                              }
                            ],
                            'langcode': 'EN',
                            'revision': 1,
                            '_rowstamp': '[0 0 0 0 0 28 8 -81]',
                            '_id': '1193-1127-1302-EAGLENA-1',
                            'orgid': 'EAGLENA',
                            'showdate': false,
                            'description': 'Response #1:',
                            'revision_localized': '1',
                            'inspformnum': '1127',
                            'showtime': false,
                            'required': false,
                            'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTMvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                            'required_localized': 'N',
                            'inspfieldid_localized': '846',
                            'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption',
                            'fieldtype': 'TR',
                            'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846',
                            'showtime_localized': 'N',
                            'inspfieldnum': '1193',
                            'inspquestionnum': '1302',
                            'sequence': 1,
                            'sequence_localized': '1',
                            'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldresult',
                            'inspfieldid': 846,
                            'hasld': false
                          },
                          {
                            'hasld_localized': 'N',
                            'showdate_localized': 'N',
                            'inspfieldoption': [
                              {
                                '_rowstamp': '[0 0 0 0 0 28 8 -78]',
                                '_id': '96',
                                'sequence': 2,
                                'description': 'example 2',
                                'inspfieldoptionid_localized': '96',
                                'sequence_localized': '2',
                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/0-96',
                                'inspfieldoptionid': 96,
                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Ng--'
                              },
                              {
                                '_rowstamp': '[0 0 0 0 0 28 8 -77]',
                                '_id': '95',
                                'sequence': 1,
                                'description': 'example 1',
                                'inspfieldoptionid_localized': '95',
                                'sequence_localized': '1',
                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/1-95',
                                'inspfieldoptionid': 95,
                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NQ--'
                              }
                            ],
                            'langcode': 'EN',
                            'revision': 1,
                            '_rowstamp': '[0 0 0 0 0 28 8 -82]',
                            '_id': '1194-1127-1302-EAGLENA-1',
                            'orgid': 'EAGLENA',
                            'showdate': false,
                            'description': 'Response #2:',
                            'inspfieldresult': [
                              {
                                'txtresponse': 'Data entered',
                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult/0-416',
                                'inspfieldresultid': 416,
                                'entereddate_localized': '3/23/17 10:38 PM',
                                'resultnum': '1184',
                                'inspfieldnum': '1194',
                                'enteredby': 'ALVIN',
                                'entereddate': '2017-03-23T22:38:59-04:00',
                                'revision': 1,
                                'inspquestionnum': '1302',
                                '_rowstamp': '[0 0 0 0 0 28 10 -61]',
                                'orgid': 'EAGLENA',
                                '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
                                'revision_localized': '1',
                                'inspfieldresultnum': '1195',
                                'siteid': 'BEDFORD',
                                'inspformnum': '1127',
                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTk0LzExMjcvMTMwMi9FQUdMRU5BLzExODQvMS9CRURGT1JE',
                                'inspfieldresultid_localized': '416'
                              }
                            ],
                            'revision_localized': '1',
                            'inspformnum': '1127',
                            'showtime': false,
                            'required': false,
                            'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTQvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                            'required_localized': 'N',
                            'inspfieldid_localized': '847',
                            'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption',
                            'fieldtype': 'TR',
                            'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847',
                            'showtime_localized': 'N',
                            'inspfieldnum': '1194',
                            'inspquestionnum': '1302',
                            'sequence': 2,
                            'sequence_localized': '2',
                            'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult',
                            'inspfieldid': 847,
                            'hasld': false
                          }
                        ],
                        'inspquestionid_localized': '942',
                        '_rowstamp': '[0 0 0 0 0 28 8 -70]',
                        '_id': '1127-1302-EAGLENA-1',
                        'sequence': 1,
                        'description': 'Question #1',
                        'groupid_localized': '1',
                        'sequence_localized': '1',
                        'inspquestionid': 942,
                        'groupid': 1,
                        'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield',
                        'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                        'hasld': false
                      }
                    ]];
var questionSetwithoutResponses = [[
                                    {
                                        'groupseq_localized': '1.00',
                                        'groupseq': 1,
                                        'hasld_localized': 'N',
                                        'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/1-943',
                                        'langcode': 'EN',
                                        'inspquestionnum': '1303',
                                        'inspquestionid_localized': '943',
                                        '_rowstamp': '[0 0 0 0 0 28 8 -66]',
                                        '_id': '1127-1303-EAGLENA-1',
                                        'sequence': 0,
                                        'description': 'Group A',
                                        'groupid_localized': '1',
                                        'sequence_localized': '0',
                                        'inspquestionid': 943,
                                        'groupid': 1,
                                        'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/1-943/inspfield',
                                        'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAzL0VBR0xFTkEvMQ--',
                                        'hasld': false,
                                        '_done': false,
                                        'listdesc': '1. Group A',
                                        'children': [
                                          {
                                            'groupseq_localized': '1.10',
                                            'groupseq': 1.1,
                                            'hasld_localized': 'N',
                                            'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942',
                                            'langcode': 'EN',
                                            'inspquestionnum': '1302',
                                            'inspfield': [
                                              {
                                                'hasld_localized': 'N',
                                                'showdate_localized': 'N',
                                                'inspfieldoption': [
                                                  {
                                                    '_rowstamp': '[0 0 0 0 0 28 8 -80]',
                                                    '_id': '94',
                                                    'sequence': 2,
                                                    'description': 'example 2',
                                                    'inspfieldoptionid_localized': '94',
                                                    'sequence_localized': '2',
                                                    'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/0-94',
                                                    'inspfieldoptionid': 94,
                                                    'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NA--'
                                                  },
                                                  {
                                                    '_rowstamp': '[0 0 0 0 0 28 8 -79]',
                                                    '_id': '93',
                                                    'sequence': 1,
                                                    'description': 'example 1',
                                                    'inspfieldoptionid_localized': '93',
                                                    'sequence_localized': '1',
                                                    'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/1-93',
                                                    'inspfieldoptionid': 93,
                                                    'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Mw--'
                                                  }
                                                ],
                                                'langcode': 'EN',
                                                'revision': 1,
                                                '_rowstamp': '[0 0 0 0 0 28 8 -81]',
                                                '_id': '1193-1127-1302-EAGLENA-1',
                                                'orgid': 'EAGLENA',
                                                'showdate': false,
                                                'description': 'Response #1:',
                                                'revision_localized': '1',
                                                'inspformnum': '1127',
                                                'showtime': false,
                                                'required': false,
                                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTMvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                                                'required_localized': 'N',
                                                'inspfieldid_localized': '846',
                                                'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption',
                                                'fieldtype': 'TR',
                                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846',
                                                'showtime_localized': 'N',
                                                'inspfieldnum': '1193',
                                                'inspquestionnum': '1302',
                                                'sequence': 1,
                                                'sequence_localized': '1',
                                                'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldresult',
                                                'inspfieldid': 846,
                                                'hasld': false
                                              },
                                              {
                                                'hasld_localized': 'N',
                                                'showdate_localized': 'N',
                                                'inspfieldoption': [
                                                  {
                                                    '_rowstamp': '[0 0 0 0 0 28 8 -78]',
                                                    '_id': '96',
                                                    'sequence': 2,
                                                    'description': 'example 2',
                                                    'inspfieldoptionid_localized': '96',
                                                    'sequence_localized': '2',
                                                    'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/0-96',
                                                    'inspfieldoptionid': 96,
                                                    'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Ng--'
                                                  },
                                                  {
                                                    '_rowstamp': '[0 0 0 0 0 28 8 -77]',
                                                    '_id': '95',
                                                    'sequence': 1,
                                                    'description': 'example 1',
                                                    'inspfieldoptionid_localized': '95',
                                                    'sequence_localized': '1',
                                                    'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/1-95',
                                                    'inspfieldoptionid': 95,
                                                    'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NQ--'
                                                  }
                                                ],
                                                'langcode': 'EN',
                                                'revision': 1,
                                                '_rowstamp': '[0 0 0 0 0 28 8 -82]',
                                                '_id': '1194-1127-1302-EAGLENA-1',
                                                'orgid': 'EAGLENA',
                                                'showdate': false,
                                                'description': 'Response #2:',
                                                'inspfieldresult': [
                                                  {
                                                    'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult/0-416',
                                                    'inspfieldresultid': 416,
                                                    'entereddate_localized': '3/23/17 11:39 PM',
                                                    'resultnum': '1184',
                                                    'inspfieldnum': '1194',
                                                    'enteredby': 'ALVIN',
                                                    'entereddate': '2017-03-23T23:39:01-04:00',
                                                    'revision': 1,
                                                    'inspquestionnum': '1302',
                                                    '_rowstamp': '[0 0 0 0 0 28 27 -49]',
                                                    'orgid': 'EAGLENA',
                                                    '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
                                                    'revision_localized': '1',
                                                    'inspfieldresultnum': '1195',
                                                    'siteid': 'BEDFORD',
                                                    'inspformnum': '1127',
                                                    'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTk0LzExMjcvMTMwMi9FQUdMRU5BLzExODQvMS9CRURGT1JE',
                                                    'inspfieldresultid_localized': '416'
                                                  }
                                                ],
                                                'revision_localized': '1',
                                                'inspformnum': '1127',
                                                'showtime': false,
                                                'required': false,
                                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTQvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                                                'required_localized': 'N',
                                                'inspfieldid_localized': '847',
                                                'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption',
                                                'fieldtype': 'TR',
                                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847',
                                                'showtime_localized': 'N',
                                                'inspfieldnum': '1194',
                                                'inspquestionnum': '1302',
                                                'sequence': 2,
                                                'sequence_localized': '2',
                                                'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult',
                                                'inspfieldid': 847,
                                                'hasld': false
                                              }
                                            ],
                                            'inspquestionid_localized': '942',
                                            '_rowstamp': '[0 0 0 0 0 28 8 -70]',
                                            '_id': '1127-1302-EAGLENA-1',
                                            'sequence': 1,
                                            'description': 'Question #1',
                                            'groupid_localized': '1',
                                            'sequence_localized': '1',
                                            'inspquestionid': 942,
                                            'groupid': 1,
                                            'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield',
                                            'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                                            'hasld': false,
                                            '_done': false,
                                            'listdesc': '1.1. Question #1'
                                          }
                                        ]
                                      },
                                      {
                                        'groupseq_localized': '1.10',
                                        'groupseq': 1.1,
                                        'hasld_localized': 'N',
                                        'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942',
                                        'langcode': 'EN',
                                        'inspquestionnum': '1302',
                                        'inspfield': [
                                          {
                                            'hasld_localized': 'N',
                                            'showdate_localized': 'N',
                                            'inspfieldoption': [
                                              {
                                                '_rowstamp': '[0 0 0 0 0 28 8 -80]',
                                                '_id': '94',
                                                'sequence': 2,
                                                'description': 'example 2',
                                                'inspfieldoptionid_localized': '94',
                                                'sequence_localized': '2',
                                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/0-94',
                                                'inspfieldoptionid': 94,
                                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NA--'
                                              },
                                              {
                                                '_rowstamp': '[0 0 0 0 0 28 8 -79]',
                                                '_id': '93',
                                                'sequence': 1,
                                                'description': 'example 1',
                                                'inspfieldoptionid_localized': '93',
                                                'sequence_localized': '1',
                                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption/1-93',
                                                'inspfieldoptionid': 93,
                                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Mw--'
                                              }
                                            ],
                                            'langcode': 'EN',
                                            'revision': 1,
                                            '_rowstamp': '[0 0 0 0 0 28 8 -81]',
                                            '_id': '1193-1127-1302-EAGLENA-1',
                                            'orgid': 'EAGLENA',
                                            'showdate': false,
                                            'description': 'Response #1:',
                                            'revision_localized': '1',
                                            'inspformnum': '1127',
                                            'showtime': false,
                                            'required': false,
                                            'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTMvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                                            'required_localized': 'N',
                                            'inspfieldid_localized': '846',
                                            'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption',
                                            'fieldtype': 'TR',
                                            'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846',
                                            'showtime_localized': 'N',
                                            'inspfieldnum': '1193',
                                            'inspquestionnum': '1302',
                                            'sequence': 1,
                                            'sequence_localized': '1',
                                            'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldresult',
                                            'inspfieldid': 846,
                                            'hasld': false
                                          },
                                          {
                                            'hasld_localized': 'N',
                                            'showdate_localized': 'N',
                                            'inspfieldoption': [
                                              {
                                                '_rowstamp': '[0 0 0 0 0 28 8 -78]',
                                                '_id': '96',
                                                'sequence': 2,
                                                'description': 'example 2',
                                                'inspfieldoptionid_localized': '96',
                                                'sequence_localized': '2',
                                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/0-96',
                                                'inspfieldoptionid': 96,
                                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85Ng--'
                                              },
                                              {
                                                '_rowstamp': '[0 0 0 0 0 28 8 -77]',
                                                '_id': '95',
                                                'sequence': 1,
                                                'description': 'example 1',
                                                'inspfieldoptionid_localized': '95',
                                                'sequence_localized': '1',
                                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption/1-95',
                                                'inspfieldoptionid': 95,
                                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRE9QVElPTi85NQ--'
                                              }
                                            ],
                                            'langcode': 'EN',
                                            'revision': 1,
                                            '_rowstamp': '[0 0 0 0 0 28 8 -82]',
                                            '_id': '1194-1127-1302-EAGLENA-1',
                                            'orgid': 'EAGLENA',
                                            'showdate': false,
                                            'description': 'Response #2:',
                                            'inspfieldresult': [
                                              {
                                                'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult/0-416',
                                                'inspfieldresultid': 416,
                                                'entereddate_localized': '3/23/17 11:39 PM',
                                                'resultnum': '1184',
                                                'inspfieldnum': '1194',
                                                'enteredby': 'ALVIN',
                                                'entereddate': '2017-03-23T23:39:01-04:00',
                                                'revision': 1,
                                                'inspquestionnum': '1302',
                                                '_rowstamp': '[0 0 0 0 0 28 27 -49]',
                                                'orgid': 'EAGLENA',
                                                '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
                                                'revision_localized': '1',
                                                'inspfieldresultnum': '1195',
                                                'siteid': 'BEDFORD',
                                                'inspformnum': '1127',
                                                'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTk0LzExMjcvMTMwMi9FQUdMRU5BLzExODQvMS9CRURGT1JE',
                                                'inspfieldresultid_localized': '416'
                                              }
                                            ],
                                            'revision_localized': '1',
                                            'inspformnum': '1127',
                                            'showtime': false,
                                            'required': false,
                                            'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTQvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                                            'required_localized': 'N',
                                            'inspfieldid_localized': '847',
                                            'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption',
                                            'fieldtype': 'TR',
                                            'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847',
                                            'showtime_localized': 'N',
                                            'inspfieldnum': '1194',
                                            'inspquestionnum': '1302',
                                            'sequence': 2,
                                            'sequence_localized': '2',
                                            'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult',
                                            'inspfieldid': 847,
                                            'hasld': false
                                          }
                                        ],
                                        'inspquestionid_localized': '942',
                                        '_rowstamp': '[0 0 0 0 0 28 8 -70]',
                                        '_id': '1127-1302-EAGLENA-1',
                                        'sequence': 1,
                                        'description': 'Question #1',
                                        'groupid_localized': '1',
                                        'sequence_localized': '1',
                                        'inspquestionid': 942,
                                        'groupid': 1,
                                        'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield',
                                        'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
                                        'hasld': false,
                                        '_done': false,
                                        'listdesc': '1.1. Question #1'
                                      }
                                    ]];

var question = [{
	  'groupseq_localized': '1.10',
	  'groupseq': 1.1,
	  'hasld_localized': 'N',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942',
	  'langcode': 'EN',
	  'inspquestionnum': '1302',
	  'inspfield': [
	    {
	      'hasld_localized': 'N',
	      'showdate_localized': 'N',
	      'langcode': 'EN',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 28 8 -81]',
	      '_id': '1193-1127-1302-EAGLENA-1',
	      'orgid': 'EAGLENA',
	      'showdate': false,
	      'description': 'Response #1:',
	      'revision_localized': '1',
	      'inspformnum': '1127',
	      'showtime': false,
	      'required': false,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTMvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	      'required_localized': 'N',
	      'inspfieldid_localized': '846',
	      'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption',
	      'fieldtype': 'TR',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846',
	      'showtime_localized': 'N',
	      'inspfieldnum': '1193',
	      'inspquestionnum': '1302',
	      'sequence': 1,
	      'sequence_localized': '1',
	      'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldresult',
	      'inspfieldid': 846,
	      'hasld': false
	    },
	    {
	      'hasld_localized': 'N',
	      'showdate_localized': 'N',
	      'langcode': 'EN',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 28 8 -82]',
	      '_id': '1194-1127-1302-EAGLENA-1',
	      'orgid': 'EAGLENA',
	      'showdate': false,
	      'description': 'Response #2:',
	      'inspfieldresult': [
	        {
	          'txtresponse': 'Data entered',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult/0-416',
	          'inspfieldresultid': 416,
	          'entereddate_localized': '3/23/17 10:38 PM',
	          'resultnum': '1184',
	          'inspfieldnum': '1194',
	          'enteredby': 'ALVIN',
	          'entereddate': '2017-03-23T22:38:59-04:00',
	          'revision': 1,
	          'inspquestionnum': '1302',
	          '_rowstamp': '[0 0 0 0 0 28 10 -61]',
	          'orgid': 'EAGLENA',
	          '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
	          'revision_localized': '1',
	          'inspfieldresultnum': '1195',
	          'siteid': 'BEDFORD',
	          'inspformnum': '1127',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTk0LzExMjcvMTMwMi9FQUdMRU5BLzExODQvMS9CRURGT1JE',
	          'inspfieldresultid_localized': '416'
	        }
	      ],
	      'revision_localized': '1',
	      'inspformnum': '1127',
	      'showtime': false,
	      'required': false,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTQvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	      'required_localized': 'N',
	      'inspfieldid_localized': '847',
	      'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption',
	      'fieldtype': 'TR',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847',
	      'showtime_localized': 'N',
	      'inspfieldnum': '1194',
	      'inspquestionnum': '1302',
	      'sequence': 2,
	      'sequence_localized': '2',
	      'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult',
	      'inspfieldid': 847,
	      'hasld': false
	    }
	  ],
	  'inspquestionid_localized': '942',
	  '_rowstamp': '[0 0 0 0 0 28 8 -70]',
	  '_id': '1127-1302-EAGLENA-1',
	  'sequence': 1,
	  'description': 'Question #1',
	  'groupid_localized': '1',
	  'sequence_localized': '1',
	  'inspquestionid': 942,
	  'groupid': 1,
	  'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield',
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	  'hasld': false
	}];

var incompletequestion = [{
	  'groupseq_localized': '1.10',
	  'groupseq': 1.1,
	  'hasld_localized': 'N',
	  'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942',
	  'langcode': 'EN',
	  'inspquestionnum': '1302',
	  'inspfield': [
	    {
	      'hasld_localized': 'N',
	      'showdate_localized': 'N',
	      'langcode': 'EN',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 28 8 -81]',
	      '_id': '1193-1127-1302-EAGLENA-1',
	      'orgid': 'EAGLENA',
	      'showdate': false,
	      'description': 'Response #1:',
	      'revision_localized': '1',
	      'inspformnum': '1127',
	      'showtime': false,
	      'required': false,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTMvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	      'required_localized': 'N',
	      'inspfieldid_localized': '846',
	      'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldoption',
	      'fieldtype': 'TR',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846',
	      'showtime_localized': 'N',
	      'inspfieldnum': '1193',
	      'inspquestionnum': '1302',
	      'sequence': 1,
	      'sequence_localized': '1',
	      'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/0-846/inspfieldresult',
	      'inspfieldid': 846,
	      'hasld': false
	    },
	    {
	      'hasld_localized': 'N',
	      'showdate_localized': 'N',
	      'langcode': 'EN',
	      'revision': 1,
	      '_rowstamp': '[0 0 0 0 0 28 8 -82]',
	      '_id': '1194-1127-1302-EAGLENA-1',
	      'orgid': 'EAGLENA',
	      'showdate': false,
	      'description': 'Response #2:',
	      'inspfieldresult': [
	        {
	          'txtresponse': '',
	          'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult/0-416',
	          'inspfieldresultid': 416,
	          'entereddate_localized': '3/23/17 10:38 PM',
	          'resultnum': '1184',
	          'inspfieldnum': '1194',
	          'enteredby': 'ALVIN',
	          'entereddate': '2017-03-23T22:38:59-04:00',
	          'revision': 1,
	          'inspquestionnum': '1302',
	          '_rowstamp': '[0 0 0 0 0 28 10 -61]',
	          'orgid': 'EAGLENA',
	          '_id': '1194-1127-1302-EAGLENA-1184-1-BEDFORD',
	          'revision_localized': '1',
	          'inspfieldresultnum': '1195',
	          'siteid': 'BEDFORD',
	          'inspformnum': '1127',
	          'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxEL0lOU1BGSUVMRFJFU1VMVC8xMTk0LzExMjcvMTMwMi9FQUdMRU5BLzExODQvMS9CRURGT1JE',
	          'inspfieldresultid_localized': '416'
	        }
	      ],
	      'revision_localized': '1',
	      'inspformnum': '1127',
	      'showtime': false,
	      'required': false,
	      'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vSU5TUEZJRUxELzExOTQvMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	      'required_localized': 'N',
	      'inspfieldid_localized': '847',
	      'inspfieldoption_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldoption',
	      'fieldtype': 'TR',
	      'localref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847',
	      'showtime_localized': 'N',
	      'inspfieldnum': '1194',
	      'inspquestionnum': '1302',
	      'sequence': 2,
	      'sequence_localized': '2',
	      'inspfieldresult_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield/1-847/inspfieldresult',
	      'inspfieldid': 847,
	      'hasld': false
	    }
	  ],
	  'inspquestionid_localized': '942',
	  '_rowstamp': '[0 0 0 0 0 28 8 -70]',
	  '_id': '1127-1302-EAGLENA-1',
	  'sequence': 1,
	  'description': 'Question #1',
	  'groupid_localized': '1',
	  'sequence_localized': '1',
	  'inspquestionid': 942,
	  'groupid': 1,
	  'inspfield_collectionref': 'http://localhost:7001/maximo/oslc/os/mxapiinspresult/_RUFHTEVOQS8xMTg0L0JFREZPUkQ-/inspectionform/0-921/inspquestion/0-942/inspfield',
	  'href': 'http://childkey#SU5TUEVDVElPTlJFU1VMVC9JTlNQRUNUSU9ORk9STS9JTlNQUVVFU1RJT04vMTEyNy8xMzAyL0VBR0xFTkEvMQ--',
	  'hasld': false
	}];
